/* auto-generated by NAPI-RS */
/* eslint-disable */
/** One opened collection. All format work is delegated to `assetstudio-core`. */
export declare class AssetStudio {
  constructor(path: string)
  /**
   * Opens a path on a libuv worker so container discovery does not block
   * the JavaScript event loop.
   */
  static openAsync(path: string): Promise<AssetStudio>
  /**
   * Opens one in-memory asset, bundle, or resource after copying the Node
   * buffer into Rust-owned immutable storage.
   */
  static fromBuffer(data: Uint8Array, name?: string | undefined | null, maximumBytes?: number | undefined | null): AssetStudio
  /** Copies a Node buffer once, then parses it on a libuv worker. */
  static fromBufferAsync(data: Uint8Array, name?: string | undefined | null, maximumBytes?: number | undefined | null): Promise<AssetStudio>
  get fileCount(): number
  get objectCount(): number
  get resourceCount(): number
  filePage(offset?: number | undefined | null, limit?: number | undefined | null): Array<FileInfo>
  objectPage(fileIndex: number, offset?: number | undefined | null, limit?: number | undefined | null): Array<ObjectInfo>
  resourcePage(offset?: number | undefined | null, limit?: number | undefined | null): Array<ResourceInfo>
  readResource(resourceIndex: number, maximumBytes?: number | undefined | null): Buffer
  readRaw(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readRawAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readText(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readTextAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTypeTreeJson(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Buffer
  readTypeTreeJsonAsync(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTypeTreeDump(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readTypeTreeDumpAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readShader(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readShaderAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readMeshObj(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readMeshObjAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTexture(fileIndex: number, pathId: bigint, mipLevel?: number | undefined | null, maximumBytes?: number | undefined | null): RgbaImage
  readTextureAsync(fileIndex: number, pathId: bigint, mipLevel?: number | undefined | null, maximumBytes?: number | undefined | null): Promise<RgbaImage>
  readTextureArray(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Array<RgbaImage>
  readTextureArrayAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Array<RgbaImage>>
  readSprite(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): RgbaImage
  readSpriteAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<RgbaImage>
}

export interface FileInfo {
  index: number
  path: string
  unityVersion: string
  objectCount: number
}

export interface ObjectInfo {
  fileIndex: number
  objectIndex: number
  sourcePath: string
  pathId: bigint
  classId: number
  byteSize: bigint
  name?: string
  container?: string
}

export interface ResourceInfo {
  index: number
  path: string
  byteSize: bigint
}

/** A decoded RGBA8 image. */
export interface RgbaImage {
  width: number
  height: number
  /**
   * Tightly packed RGBA8 rows in display order: the first row is the top
   * edge of the image, matching the Python binding and the CLI's encoded
   * output. `Texture2D` decoders work bottom-up, so these rows have already
   * been flipped.
   */
  pixels: Buffer
}
