/* auto-generated by NAPI-RS */
/* eslint-disable */
/** One opened collection. All format work is delegated to `assetstudio-core`. */
export declare class AssetStudio {
  constructor(path: string)
  /**
   * Opens a path, parsing against `unityVersion` instead of the version the
   * files declare.
   *
   * Needed for files whose own version was stripped at build time, where a
   * reader has nothing to key its layout decisions on.
   */
  static openWithVersion(path: string, unityVersion: string): AssetStudio
  /**
   * Writes the animated FBX, decoding ACL tracks through a caller-supplied
   * decoder.
   *
   * Core ships no ACL decoder. Without one a clip whose samples are ACL
   * compressed contributes nothing to the FBX; with one its tracks are
   * validated on the way back in -- shape, ordering and budgets are Core's
   * checks, not the caller's promises.
   *
   * Asynchronous for the same reason as the Oodle entry point: the callback
   * runs on the event loop while a worker waits for it.
   */
  readFbxWithAclDecoder(decoder: AclCallback, maximumBytes?: number | undefined | null): Promise<Buffer>
  /**
   * Opens a path whose bundles are Oodle-compressed, using a
   * caller-supplied decoder.
   *
   * Asynchronous by necessity, not for convenience: the decoder runs on the
   * JavaScript event loop while a worker waits for it, so calling this
   * synchronously would block the loop that has to run the callback.
   *
   * The callback receives the compressed bytes and the exact expected output
   * length, and must return precisely that many bytes.
   */
  static openWithOodle(path: string, decoder: OodleCallback): Promise<AssetStudio>
  /**
   * Opens a path on a libuv worker so container discovery does not block
   * the JavaScript event loop.
   */
  static openAsync(path: string): Promise<AssetStudio>
  /**
   * Opens one in-memory asset, bundle, or resource after copying the Node
   * buffer into Rust-owned immutable storage.
   */
  static fromBuffer(data: Uint8Array, name?: string | undefined | null, maximumBytes?: number | undefined | null): AssetStudio
  /** Copies a Node buffer once, then parses it on a libuv worker. */
  static fromBufferAsync(data: Uint8Array, name?: string | undefined | null, maximumBytes?: number | undefined | null): Promise<AssetStudio>
  get fileCount(): number
  get objectCount(): number
  get resourceCount(): number
  filePage(offset?: number | undefined | null, limit?: number | undefined | null): Array<FileInfo>
  objectPage(fileIndex: number, offset?: number | undefined | null, limit?: number | undefined | null): Array<ObjectInfo>
  resourcePage(offset?: number | undefined | null, limit?: number | undefined | null): Array<ResourceInfo>
  readResource(resourceIndex: number, maximumBytes?: number | undefined | null): Buffer
  readRaw(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readRawAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readText(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readTextAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTypeTreeJson(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Buffer
  readTypeTreeJsonAsync(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTypeTreeDump(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readTypeTreeDumpAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readShader(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readShaderAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readMeshObj(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readMeshObjAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTexture(fileIndex: number, pathId: bigint, mipLevel?: number | undefined | null, maximumBytes?: number | undefined | null): RgbaImage
  readTextureAsync(fileIndex: number, pathId: bigint, mipLevel?: number | undefined | null, maximumBytes?: number | undefined | null): Promise<RgbaImage>
  readTextureArray(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Array<RgbaImage>
  readTextureArrayAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Array<RgbaImage>>
  readSprite(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): RgbaImage
  readSpriteAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<RgbaImage>
  /** Reads an `AudioClip`'s stored payload without transcoding it. */
  readAudio(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AudioClip
  /** Reads the identity of a `MonoScript`. */
  readMonoScript(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): MonoScript
  /**
   * Reads a `Material`'s shader reference and the names of its properties.
   *
   * Property values are deliberately not flattened here: they are typed
   * per sheet and a caller that needs them is better served by the Rust or
   * Python API than by a lossy JavaScript projection.
   */
  readMaterial(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Material
  /** Reads the scene list a `BuildSettings` object records. */
  readBuildSettings(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BuildSettings
  /** Reads the company and product names from a `PlayerSettings` object. */
  readPlayerSettings(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): PlayerSettings
  /** Reads an `Avatar`'s skeleton summary. */
  readAvatar(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Avatar
  /**
   * Opens several in-memory inputs as one collection.
   *
   * A serialized file and the `.resS` its textures and audio stream from are
   * separate files; opening them one at a time leaves every streamed payload
   * unresolvable, so a caller holding both in memory needs to pass them
   * together.
   */
  static fromBuffers(inputs: Array<MemoryInput>, maximumBytes?: number | undefined | null): AssetStudio
  /**
   * Reads one checked byte range of a resource without materializing the
   * rest, which is how a caller pulls a single texture out of a large
   * `.resS`.
   */
  readResourceRange(resourceIndex: number, offset: bigint, length: bigint, maximumBytes?: number | undefined | null): Buffer
  /** Finds a resource by the path a serialized file references it through. */
  resourceIndexByPath(path: string): number | null
  /** Assembles the `GameObject` hierarchy across every loaded file. */
  scene(maximumGameObjects?: number | undefined | null): Array<SceneNode>
  /**
   * Writes the whole collection as static ASCII FBX 7.4.
   *
   * Ordinary and skinned renderer geometry, direct and hash-recovered bones
   * and static blend shapes. Animation and textures are separate concerns
   * and are not included.
   */
  readStaticFbx(maximumBytes?: number | undefined | null): Buffer
  /**
   * The same static scene in FBX 7.4's binary encoding.
   *
   * Some importers accept only the binary form, and it is smaller and faster
   * to parse. The scene is identical to `readStaticFbx`.
   */
  readStaticFbxBinary(maximumBytes?: number | undefined | null): Buffer
  /**
   * Reads a `CubismPhysicsController` and writes its physics3.json.
   *
   * `motionFps` is the fallback the converter uses when the rig carries no
   * frame rate of its own, matching the managed extractor's argument.
   */
  readCubismPhysics(fileIndex: number, pathId: bigint, motionFps?: number | undefined | null, maximumBytes?: number | undefined | null): CubismDocument
  /** Reads a `CubismExpressionData` and writes its exp3.json. */
  readCubismExpression(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): CubismDocument
  /** Reads a `CubismFadeMotionData` and writes its motion3.json. */
  readCubismFadeMotion(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): CubismDocument
  /**
   * Enumerates the `GameObject` branches a split-objects export would write.
   *
   * The whole-collection FBX calls put every model in one file; these name
   * the branches so a caller can write one file each, which is what the
   * CLI's `split-objects` does.
   */
  splitObjectFbxCandidates(): Array<FbxCandidate>
  /** Enumerates the branches an Animator owns. */
  animatorFbxCandidates(): Array<FbxCandidate>
  /** Writes one selected `GameObject` branch as FBX. */
  readGameObjectFbx(fileIndex: number, pathId: bigint, includeAnimations?: boolean | undefined | null, maximumBytes?: number | undefined | null): Buffer
  /** Reads a `Font`'s resident payload. */
  readFont(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BinaryAsset
  /** Reads the resident Ogg payload from a legacy `MovieTexture`. */
  readMovieTexture(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BinaryAsset
  /** Reads a `VideoClip`'s resident or external payload. */
  readVideoClip(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BinaryAsset
  /**
   * Exports every supported object into `outputRoot`.
   *
   * The Core exporter writes atomically and never overwrites unless asked,
   * and a failure on one object is recorded rather than raised so a single
   * unreadable asset does not cost the run.
   */
  export(outputRoot: string, overwrite?: boolean | undefined | null): ExportReport
  /**
   * Recursively extracts one file or directory tree without loading it.
   *
   * Child symlinks are never followed and every archive path is made
   * relative before it is joined to the output root, so a hostile entry
   * cannot escape it.
   */
  static extract(input: string, outputRoot: string, overwrite?: boolean | undefined | null): ExtractionReport
  /** Reads an `AnimationClip`'s shape without materializing its keyframes. */
  readAnimationClipInfo(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AnimationClipInfo
  /** Reads an `AnimatorController`'s identity and the clips it references. */
  readAnimatorController(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AnimatorControllerInfo
  /**
   * Discovers the Live2D models in the collection.
   *
   * Only the shape of each package is returned. Materializing the files --
   * the MOC, textures and JSON -- is a separate concern and belongs behind
   * an explicit output budget.
   */
  live2DPackages(): Array<Live2DPackageInfo>
  /**
   * Writes the collection as ASCII FBX 7.4 including its animation tracks.
   *
   * The static variant omits animation deliberately; this is the one a
   * caller wants for a rigged model.
   */
  readFbx(maximumBytes?: number | undefined | null): Buffer
  /** The same animated scene in FBX 7.4's binary encoding. */
  readFbxBinary(maximumBytes?: number | undefined | null): Buffer
  /**
   * Materializes every Live2D package: the MOC, the model3 manifest, the
   * mip-zero texture PNGs, and the expression, motion, physics, pose and
   * display-info JSON where their verified fields are present.
   *
   * Returned in memory rather than written, so the caller decides where the
   * files land and stays inside whatever budget it set.
   */
  readLive2DPackages(maximumBytes?: number | undefined | null): Array<Live2DPackageFiles>
  /**
   * Writes the collection as ASCII FBX with its animations and returns the
   * material textures it references.
   *
   * The FBX names each texture by file name, so the returned files have to
   * be written beside it for those references to resolve. They come back
   * rather than being written because this call has no directory of its own
   * and where they land is the caller's decision.
   */
  readFbxWithTextures(maximumBytes?: number | undefined | null): TexturedFbx
  /**
   * Inspects an `AnimationClip`'s ACL blob without decompressing it.
   *
   * Core ships no ACL decoder, so this is what a caller needs to decide
   * whether its own decoder can handle the blob before asking for it.
   */
  readAclTracks(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AclTracks
  /**
   * Reads a `MonoBehaviour` as JSON, resolving its stripped managed fields
   * through caller-supplied schemas.
   *
   * A shipped build strips the managed type layout, so without a schema only
   * the engine-owned prefix can be read. The schemas are data: they are
   * matched by assembly, namespace, class and optionally Unity version, and
   * nothing in them is executed.
   */
  readMonoBehaviourJsonWithSchemas(fileIndex: number, pathId: bigint, schemas: Array<MonoBehaviourSchema>, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Buffer
}

/**
 * Frame-major scalar curves an injected ACL decoder returns.
 *
 * `bindingIndices[column]` is the absolute Unity binding scalar index for
 * `values[frame * bindingIndices.length + column]`, and the indices must be
 * strictly increasing.
 */
export interface AclDecodedClip {
  times: Array<number>
  bindingIndices: Array<number>
  values: Array<number>
  /** Binding offset for the ordinary streamed curves that follow. */
  followingCurveOffset: number
}

/** What an injected ACL decoder is asked to decode. */
export interface AclDecodeRequest {
  frameCount: number
  boneCount: number
  sampleRate: number
  declaredCurveCount?: number
  useFastSampleMode?: boolean
  /** The validated compressed-track bytes. */
  compressedTracks: Buffer
  /** Tuanjie's decoder map, empty when the clip carries none. */
  decoderMap: Array<number>
}

/**
 * The header of one ACL compressed-track blob.
 *
 * Enough to decide whether a caller's decoder can handle it, without
 * decompressing anything.
 *
 * The state flags stay separate booleans rather than the packed bits Core
 * keeps them in: this is a JavaScript-facing shape, and a bitfield would only
 * move the unpacking to the other side.
 */
export interface AclTracks {
  declaredSize: number
  storedHash: number
  version: number
  trackType: string
  trackCount: number
  samplesPerTrack: number
  sampleRate: number
  decompressedValueCount: bigint
  hasMetadata: boolean
  isWrapOptimized: boolean
  hasDatabase: boolean
  hasStrippedKeyframes: boolean
}

/**
 * An `AnimationClip`'s shape, without materializing its keyframes.
 *
 * Separate booleans rather than a bitfield: this is a JavaScript-facing shape
 * and a bitfield would only move the decoding to the other side.
 */
export interface AnimationClipInfo {
  name: string
  sampleRate: number
  wrapMode: number
  legacy: boolean
  compressed: boolean
  rotationCurveCount: number
  positionCurveCount: number
  scaleCurveCount: number
  eulerCurveCount: number
  floatCurveCount: number
  /** Present when the clip carries muscle (humanoid) data. */
  hasMuscleClip: boolean
  /** Present when the clip's samples live in a sibling resource file. */
  hasStreamingInfo: boolean
}

/** An `AnimatorController`'s identity and the clips it references. */
export interface AnimatorControllerInfo {
  name: string
  /** Transform-path strings the controller's bindings resolve through. */
  tosEntryCount: number
  animationClipPathIds: Array<bigint>
}

/** One `AudioClip`'s stored payload and the extension its container implies. */
export interface AudioClip {
  name: string
  /** The extension the stored bytes carry, `.fsb` or `.wav` for example. */
  extension: string
  /** True when the payload is already a playable RIFF/WAVE stream. */
  isDirectWav: boolean
  data: Buffer
}

/** An `Avatar`'s skeleton summary. */
export interface Avatar {
  name: string
  /** The size the object declares for its constant block. */
  declaredSize: number
  /**
   * Bone path entries, retained in order so duplicate hashes keep Unity's
   * first-hit behaviour.
   */
  pathCount: number
  hasHumanDescription: boolean
}

/**
 * A resident binary asset: a `Font`, a legacy `MovieTexture`, or a `VideoClip`.
 *
 * All three are a name and a blob whose format the file declares, so one shape
 * covers them rather than three that differ only in what they are called.
 */
export interface BinaryAsset {
  name: string
  /** What the payload is, as the reader classified it. */
  kind: string
  /** The extension the stored bytes carry, `.ttf` or `.ogg` for example. */
  extension: string
  data: Buffer
}

/** The scene lists a `BuildSettings` object records. */
export interface BuildSettings {
  /** Pre-5.x level paths, absent on newer layouts. */
  levels?: Array<string>
  /** 5.x and newer scene paths, absent on older layouts. */
  scenes?: Array<string>
}

/**
 * One Cubism document produced from a single behaviour.
 *
 * The bytes are the document itself; the counts alongside are what a caller
 * would otherwise have to parse the JSON to learn.
 */
export interface CubismDocument {
  name: string
  /** The document's own JSON text. */
  json: Buffer
  /**
   * Sub-rigs for physics, parameters for an expression, curves for a
   * motion. Zero for a document that has no such notion.
   */
  entryCount: number
}

/** One object the exporter could not write, and why. */
export interface ExportFailure {
  source: string
  pathId: bigint
  classId: number
  error: string
}

/** One object the exporter wrote. */
export interface ExportRecord {
  source: string
  pathId: bigint
  classId: number
  outputPath: string
  /** What the bytes are, `image_png` or `mesh_obj` for example. */
  payloadKind: string
}

/**
 * What an export run produced. Failures are reported rather than thrown so
 * one unreadable object does not cost the whole run.
 */
export interface ExportReport {
  exported: Array<ExportRecord>
  failures: Array<ExportFailure>
}

/** What an extraction run produced. */
export interface ExtractionReport {
  extractedCount: number
  skippedExistingCount: number
  failureCount: number
  outputBytes: bigint
}

/** One `GameObject` branch that can be exported as its own FBX. */
export interface FbxCandidate {
  fileIndex: number
  pathId: bigint
  /** The Animator that owns this branch, when one does. */
  animatorFileIndex?: number
  animatorPathId?: bigint
  name: string
}

export interface FileInfo {
  index: number
  path: string
  unityVersion: string
  objectCount: number
}

/** One file belonging to a materialized Live2D package. */
export interface Live2DFile {
  /** Path relative to the package directory. */
  fileName: string
  data: Buffer
}

/** One materialized Live2D model: every file it needs, in memory. */
export interface Live2DPackageFiles {
  name: string
  directoryName: string
  files: Array<Live2DFile>
}

/** One Live2D model discovered in the collection. */
export interface Live2DPackageInfo {
  name: string
  directoryName: string
  mocFileName: string
  textureCount: number
  expressionCount: number
  motionCount: number
  hasPhysics: boolean
  hasPose: boolean
  hasDisplayInfo: boolean
}

/** A `Material`'s shader reference and its named property sheets. */
export interface Material {
  name: string
  shaderFileId: number
  shaderPathId: bigint
  textureProperties: Array<string>
  floatProperties: Array<string>
  colorProperties: Array<string>
}

/** One in-memory input for a multi-file open. */
export interface MemoryInput {
  name: string
  data: Buffer
}

/** A complete object schema for one managed script type. */
export interface MonoBehaviourSchema {
  assemblyName: string
  className: string
  namespace?: string
  /**
   * Exact Unity version this schema was generated for. Omit for a schema
   * that applies to every version.
   */
  unityVersion?: string
  nodes: Array<SchemaNode>
}

/**
 * The identity fields of a `MonoScript`, which name the type a
 * `MonoBehaviour` deserializes as.
 */
export interface MonoScript {
  name: string
  className: string
  namespace: string
  assemblyName: string
  executionOrder?: number
}

export interface ObjectInfo {
  fileIndex: number
  objectIndex: number
  sourcePath: string
  pathId: bigint
  classId: number
  byteSize: bigint
  name?: string
  container?: string
}

/** The identity fields of a `PlayerSettings` object. */
export interface PlayerSettings {
  companyName: string
  productName: string
}

export interface ResourceInfo {
  index: number
  path: string
  byteSize: bigint
}

/** A decoded RGBA8 image. */
export interface RgbaImage {
  width: number
  height: number
  /**
   * Tightly packed RGBA8 rows in display order: the first row is the top
   * edge of the image, matching the Python binding and the CLI's encoded
   * output. `Texture2D` decoders work bottom-up, so these rows have already
   * been flipped.
   */
  pixels: Buffer
}

/**
 * One `GameObject` in the assembled hierarchy.
 *
 * The component flags are separate booleans rather than a bitfield because
 * this is a JavaScript-facing shape and a bitfield would need decoding on the
 * other side.
 */
export interface SceneNode {
  fileIndex: number
  pathId: bigint
  name: string
  /** Absent for a `GameObject` with no `Transform`, which cannot be placed. */
  parentPathId?: bigint
  childCount: number
  hasTransform: boolean
  hasMeshRenderer: boolean
  hasSkinnedMeshRenderer: boolean
  hasAnimator: boolean
}

/**
 * One node of a trusted managed object schema.
 *
 * Reconstructed by an offline tool; nothing here executes asset-controlled
 * code. `align` sets the four-byte alignment flag Unity's own trees carry.
 */
export interface SchemaNode {
  typeName: string
  fieldName: string
  /** Nesting depth, zero for the root. */
  level: number
  align: boolean
}

/** An FBX plus the texture files it references by name. */
export interface TexturedFbx {
  fbx: Buffer
  /** Each must be written beside the FBX for its reference to resolve. */
  textures: Array<Live2DFile>
  /**
   * Texture references this reader could not resolve or decode, with the
   * reason. Reported rather than raised so one bad texture does not cost the
   * model.
   */
  skipped: Array<string>
}
