[package]
name = "assetstudio-python"
description = "Native Python bindings for unity-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]
test = false
doctest = false

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
assetstudio-core = { version = "0.1.0", path = "../assetstudio-core" }
pyo3 = { version = "0.29.0", features = ["abi3-py39"] }

[lints]
workspace = true
