[package]
name = "assetstudio-cli"
description = "Native Rust command-line frontend for AssetStudio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[[bin]]
name = "assetstudio"
path = "src/main.rs"

[dependencies]
assetstudio-core = { version = "0.1.0", path = "../assetstudio-core" }

[lints]
workspace = true
