"""Native, bounded Unity asset parsing powered by AssetStudio's Rust core."""

from typing import Callable as _Callable, Optional as _Optional

from ._native import (
    __version__,
    AclCompressedTracks,
    AclDecodedClip,
    AnimationClip,
    AnimatorController,
    AssetStudio,
    Avatar,
    AudioClip,
    BinaryAsset,
    BuildSettings,
    CubismExpression,
    CubismExpressionParameter,
    CubismClipMotion,
    CubismMotionTargets,
    CubismFadeMotion,
    CubismDisplayInfo,
    CubismPhysics,
    CubismPosePart,
    ExportLimits,
    ExportReport,
    ExtractionFailure,
    ExtractionLimits,
    ExtractionRecord,
    ExtractionReport,
    ExtractionSkip,
    FbxCandidate,
    FileInfo,
    FileIterator,
    Live2dDiagnostic,
    Live2dExpressionFile,
    Live2dJsonFile,
    Live2dMotionFile,
    Live2dPackage,
    Live2dPackageSet,
    Live2dTexture,
    Material,
    ModelFile,
    ModelObj,
    ModelTextureLimits,
    MonoBehaviourJson,
    MonoBehaviourSchema,
    MonoBehaviourSchemas,
    MonoScript,
    ObjectInfo,
    ObjectIterator,
    PlayerSettings,
    RgbaImage,
    ResourceInfo,
    ResourceIterator,
    SceneLimits,
    SceneNode,
    TexturedFbx,
    extract,
)

OodleDecoder = _Callable[[bytes, int], bytes]
AclDecoder = _Callable[
    [bytes, list[int], int, int, float, _Optional[int], _Optional[bool]],
    tuple[list[float], list[int], list[float], int],
]

__all__ = [
    "__version__",
    "AclDecoder",
    "AclCompressedTracks",
    "AclDecodedClip",
    "AnimationClip",
    "AnimatorController",
    "AssetStudio",
    "Avatar",
    "AudioClip",
    "BinaryAsset",
    "BuildSettings",
    "CubismExpression",
    "CubismExpressionParameter",
    "CubismClipMotion",
    "CubismMotionTargets",
    "CubismFadeMotion",
    "CubismDisplayInfo",
    "CubismPhysics",
    "CubismPosePart",
    "ExportLimits",
    "ExportReport",
    "ExtractionFailure",
    "ExtractionLimits",
    "ExtractionRecord",
    "ExtractionReport",
    "ExtractionSkip",
    "FbxCandidate",
    "FileInfo",
    "FileIterator",
    "Live2dDiagnostic",
    "Live2dExpressionFile",
    "Live2dJsonFile",
    "Live2dMotionFile",
    "Live2dPackage",
    "Live2dPackageSet",
    "Live2dTexture",
    "Material",
    "ModelFile",
    "ModelObj",
    "ModelTextureLimits",
    "MonoBehaviourJson",
    "MonoBehaviourSchema",
    "MonoBehaviourSchemas",
    "MonoScript",
    "ObjectInfo",
    "ObjectIterator",
    "OodleDecoder",
    "PlayerSettings",
    "RgbaImage",
    "ResourceInfo",
    "ResourceIterator",
    "SceneLimits",
    "SceneNode",
    "TexturedFbx",
    "extract",
]
