from os import PathLike
from typing import Callable, Iterator, Optional, Union

OodleDecoder = Callable[[bytes, int], bytes]
AclDecoder = Callable[
    [bytes, list[int], int, int, float, Optional[int], Optional[bool]],
    tuple[list[float], list[int], list[float], int],
]

__version__: str

class FileInfo:
    @property
    def index(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def unity_version(self) -> str: ...
    @property
    def object_count(self) -> int: ...

class ObjectInfo:
    @property
    def file_index(self) -> int: ...
    @property
    def object_index(self) -> int: ...
    @property
    def source_path(self) -> str: ...
    @property
    def path_id(self) -> int: ...
    @property
    def class_id(self) -> int: ...
    @property
    def byte_size(self) -> int: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def container(self) -> Optional[str]: ...

class ResourceInfo:
    @property
    def index(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def byte_size(self) -> int: ...

class FileIterator(Iterator[FileInfo]):
    def __iter__(self) -> FileIterator: ...
    def __next__(self) -> FileInfo: ...

class ObjectIterator(Iterator[ObjectInfo]):
    def __iter__(self) -> ObjectIterator: ...
    def __next__(self) -> ObjectInfo: ...

class ResourceIterator(Iterator[ResourceInfo]):
    def __iter__(self) -> ResourceIterator: ...
    def __next__(self) -> ResourceInfo: ...

class MonoBehaviourSchema:
    def __new__(
        cls,
        assembly_name: str,
        class_name: str,
        nodes: list[tuple[str, str, int, bool]],
        *,
        namespace: Optional[str] = None,
        unity_version: Optional[str] = None,
    ) -> MonoBehaviourSchema: ...
    @property
    def assembly_name(self) -> str: ...
    @property
    def namespace(self) -> str: ...
    @property
    def class_name(self) -> str: ...
    @property
    def unity_version(self) -> Optional[str]: ...
    @property
    def node_count(self) -> int: ...

class MonoBehaviourSchemas:
    def __new__(
        cls,
        schemas: list[MonoBehaviourSchema],
    ) -> MonoBehaviourSchemas: ...
    @property
    def schema_count(self) -> int: ...

class BuildSettings:
    @property
    def path_id(self) -> int: ...
    @property
    def levels(self) -> Optional[list[str]]: ...
    @property
    def scenes(self) -> Optional[list[str]]: ...

class PlayerSettings:
    @property
    def path_id(self) -> int: ...
    @property
    def company_name(self) -> str: ...
    @property
    def product_name(self) -> str: ...

class AnimationClip:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def legacy(self) -> bool: ...
    @property
    def compressed(self) -> bool: ...
    @property
    def use_high_quality_curve(self) -> bool: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def wrap_mode(self) -> int: ...
    @property
    def rotation_curve_count(self) -> int: ...
    @property
    def euler_curve_count(self) -> int: ...
    @property
    def position_curve_count(self) -> int: ...
    @property
    def scale_curve_count(self) -> int: ...
    @property
    def float_curve_count(self) -> int: ...
    @property
    def pptr_curve_count(self) -> int: ...
    @property
    def muscle_clip_size(self) -> int: ...
    @property
    def muscle_present(self) -> bool: ...
    @property
    def streamed_curve_count(self) -> Optional[int]: ...
    @property
    def dense_curve_count(self) -> Optional[int]: ...
    @property
    def constant_value_count(self) -> Optional[int]: ...
    @property
    def acl_present(self) -> bool: ...
    @property
    def acl_frame_count(self) -> Optional[int]: ...
    @property
    def acl_bone_count(self) -> Optional[int]: ...
    @property
    def acl_sample_rate(self) -> Optional[float]: ...
    @property
    def acl_curve_count(self) -> Optional[int]: ...
    @property
    def acl_track_byte_count(self) -> Optional[int]: ...
    @property
    def acl_decoder_count(self) -> Optional[int]: ...
    @property
    def acl_use_fast_sample_mode(self) -> Optional[bool]: ...
    @property
    def streaming_offset(self) -> Optional[int]: ...
    @property
    def streaming_size(self) -> Optional[int]: ...
    @property
    def streaming_path(self) -> Optional[str]: ...

class LegacyAnimation:
    @property
    def path_id(self) -> int: ...
    @property
    def game_object(self) -> tuple[int, int]: ...
    @property
    def enabled(self) -> int: ...
    @property
    def default_clip(self) -> tuple[int, int]: ...
    @property
    def clips(self) -> list[tuple[int, int]]: ...
    @property
    def trailing_bytes(self) -> int: ...

class AnimatorOverrideController:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def controller(self) -> tuple[int, int]: ...
    @property
    def clip_overrides(
        self,
    ) -> list[tuple[tuple[int, int], tuple[int, int]]]: ...
    @property
    def trailing_bytes(self) -> int: ...

class AssetBundle:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def object_name(self) -> str: ...
    @property
    def asset_bundle_name(self) -> Optional[str]: ...
    @property
    def preload_table(self) -> list[tuple[int, int]]: ...
    @property
    def container(
        self,
    ) -> list[tuple[str, int, int, tuple[int, int]]]: ...
    @property
    def dependencies(self) -> list[str]: ...
    @property
    def is_streamed_scene_asset_bundle(self) -> bool: ...

class ResourceManager:
    @property
    def path_id(self) -> int: ...
    @property
    def container(self) -> list[tuple[str, tuple[int, int]]]: ...

class PreloadData:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def assets(self) -> list[tuple[int, int]]: ...

class SpriteAtlasRenderDataKey:
    @property
    def guid_bytes(self) -> bytes: ...
    @property
    def value(self) -> int: ...

class SpriteAtlasSecondaryTexture:
    @property
    def texture(self) -> tuple[int, int]: ...
    @property
    def name(self) -> str: ...

class SpriteAtlasRenderData:
    @property
    def key(self) -> SpriteAtlasRenderDataKey: ...
    @property
    def texture(self) -> tuple[int, int]: ...
    @property
    def alpha_texture(self) -> tuple[int, int]: ...
    @property
    def texture_rect(self) -> tuple[float, float, float, float]: ...
    @property
    def texture_rect_offset(self) -> tuple[float, float]: ...
    @property
    def atlas_rect_offset(self) -> tuple[float, float]: ...
    @property
    def uv_transform(self) -> tuple[float, float, float, float]: ...
    @property
    def downscale_multiplier(self) -> float: ...
    @property
    def settings_raw(self) -> int: ...
    @property
    def packed(self) -> bool: ...
    @property
    def packing_mode(self) -> int: ...
    @property
    def packing_rotation(self) -> int: ...
    @property
    def mesh_type(self) -> int: ...
    @property
    def secondary_textures(self) -> Optional[list[SpriteAtlasSecondaryTexture]]: ...

class SpriteAtlas:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def packed_sprites(self) -> list[tuple[int, int]]: ...
    @property
    def packed_sprite_names(self) -> list[str]: ...
    @property
    def render_data_entries(self) -> list[SpriteAtlasRenderData]: ...
    @property
    def tag(self) -> str: ...
    @property
    def is_variant(self) -> bool: ...

class SpriteSettings:
    @property
    def raw(self) -> int: ...
    @property
    def packed(self) -> bool: ...
    @property
    def packing_mode(self) -> str: ...
    @property
    def packing_rotation(self) -> int: ...
    @property
    def mesh_type(self) -> str: ...

class SpriteMetadataLimits:
    def __new__(
        cls,
        *,
        maximum_entries: int = 1_000_000,
        maximum_string_bytes: int = 16_777_216,
        maximum_total_string_bytes: int = 33_554_432,
        maximum_mesh_bytes: int = 536_870_912,
    ) -> SpriteMetadataLimits: ...
    @property
    def maximum_entries(self) -> int: ...
    @property
    def maximum_string_bytes(self) -> int: ...
    @property
    def maximum_total_string_bytes(self) -> int: ...
    @property
    def maximum_mesh_bytes(self) -> int: ...

class SpriteSecondaryTexture:
    @property
    def texture(self) -> tuple[int, int]: ...
    @property
    def name(self) -> str: ...

class SpriteRenderData:
    @property
    def texture(self) -> tuple[int, int]: ...
    @property
    def alpha_texture(self) -> tuple[int, int]: ...
    @property
    def secondary_textures(self) -> list[SpriteSecondaryTexture]: ...
    @property
    def texture_rect(self) -> tuple[float, float, float, float]: ...
    @property
    def texture_rect_offset(self) -> tuple[float, float]: ...
    @property
    def atlas_rect_offset(self) -> tuple[float, float]: ...
    @property
    def settings(self) -> SpriteSettings: ...
    @property
    def uv_transform(self) -> tuple[float, float, float, float]: ...
    @property
    def downscale_multiplier(self) -> float: ...
    @property
    def mesh_triangles(
        self,
    ) -> list[
        tuple[
            tuple[float, float],
            tuple[float, float],
            tuple[float, float],
        ]
    ]: ...

class SpriteMetadata:
    @property
    def object_index(self) -> int: ...
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def rect(self) -> tuple[float, float, float, float]: ...
    @property
    def offset(self) -> tuple[float, float]: ...
    @property
    def border(self) -> tuple[float, float, float, float]: ...
    @property
    def pixels_to_units(self) -> float: ...
    @property
    def pivot(self) -> tuple[float, float]: ...
    @property
    def extrude(self) -> int: ...
    @property
    def is_polygon(self) -> bool: ...
    @property
    def render_data_key(self) -> Optional[SpriteAtlasRenderDataKey]: ...
    @property
    def atlas_tags(self) -> list[str]: ...
    @property
    def sprite_atlas(self) -> tuple[int, int]: ...
    @property
    def render_data(self) -> SpriteRenderData: ...

class AclCompressedTracks:
    @property
    def declared_size(self) -> int: ...
    @property
    def stored_hash(self) -> int: ...
    @property
    def version(self) -> int: ...
    @property
    def track_type(self) -> str: ...
    @property
    def num_tracks(self) -> int: ...
    @property
    def num_samples_per_track(self) -> int: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def decompressed_value_count(self) -> int: ...
    @property
    def has_metadata(self) -> bool: ...
    @property
    def is_wrap_optimized(self) -> bool: ...
    @property
    def has_database(self) -> bool: ...
    @property
    def has_stripped_keyframes(self) -> bool: ...

class AclDecodedClip:
    @property
    def times(self) -> list[float]: ...
    @property
    def binding_indices(self) -> list[int]: ...
    @property
    def values(self) -> list[float]: ...
    @property
    def following_curve_offset(self) -> int: ...

class AnimatorController:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def controller_size(self) -> int: ...
    @property
    def layer_count(self) -> int: ...
    @property
    def state_machine_count(self) -> int: ...
    @property
    def value_count(self) -> int: ...
    @property
    def entity_id_count(self) -> Optional[int]: ...
    @property
    def tos(self) -> list[tuple[int, str]]: ...
    @property
    def animation_clips(self) -> list[tuple[int, int]]: ...

class Avatar:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def declared_avatar_size(self) -> int: ...
    @property
    def skeleton_node_count(self) -> int: ...
    @property
    def human_skeleton_node_count(self) -> int: ...
    @property
    def path_count(self) -> int: ...
    @property
    def paths(self) -> list[tuple[int, str]]: ...
    @property
    def has_human_description(self) -> bool: ...
    @property
    def human_bone_count(self) -> int: ...
    @property
    def skeleton_bone_count(self) -> int: ...
    @property
    def root_motion_bone_name(self) -> Optional[str]: ...

class CubismExpressionParameter:
    @property
    def id(self) -> str: ...
    @property
    def value(self) -> float: ...
    @property
    def blend(self) -> str: ...

class CubismExpression:
    @property
    def path_id(self) -> int: ...
    @property
    def source_name(self) -> str: ...
    @property
    def expression_type(self) -> str: ...
    @property
    def fade_in_time(self) -> float: ...
    @property
    def fade_out_time(self) -> float: ...
    @property
    def parameters(self) -> list[CubismExpressionParameter]: ...
    @property
    def json(self) -> bytes: ...

class CubismPosePart:
    @property
    def path_id(self) -> int: ...
    @property
    def group_index(self) -> int: ...
    @property
    def links(self) -> list[str]: ...

class CubismDisplayInfo:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def display_name(self) -> Optional[str]: ...
    @property
    def effective_name(self) -> str: ...

class CubismPhysics:
    @property
    def path_id(self) -> int: ...
    @property
    def fps(self) -> float: ...
    @property
    def gravity(self) -> tuple[float, float]: ...
    @property
    def wind(self) -> tuple[float, float]: ...
    @property
    def sub_rig_count(self) -> int: ...
    @property
    def input_count(self) -> int: ...
    @property
    def output_count(self) -> int: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def json(self) -> bytes: ...

class CubismFadeMotion:
    @property
    def path_id(self) -> int: ...
    @property
    def source_name(self) -> str: ...
    @property
    def motion_name(self) -> str: ...
    @property
    def fade_in_time(self) -> float: ...
    @property
    def fade_out_time(self) -> float: ...
    @property
    def motion_length(self) -> float: ...
    @property
    def curve_count(self) -> int: ...
    @property
    def keyframe_count(self) -> int: ...
    @property
    def json(self) -> bytes: ...

class CubismClipMotion:
    @property
    def file_index(self) -> int: ...
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def duration(self) -> float: ...
    @property
    def fps(self) -> float: ...
    @property
    def curve_count(self) -> int: ...
    @property
    def keyframe_count(self) -> int: ...
    @property
    def event_count(self) -> int: ...
    @property
    def json(self) -> bytes: ...

class CubismMotionTargets:
    def __new__(
        cls,
        *,
        parameters: Optional[list[str]] = None,
        parts: Optional[list[str]] = None,
    ) -> CubismMotionTargets: ...
    @property
    def parameters(self) -> list[str]: ...
    @property
    def parts(self) -> list[str]: ...

class RgbaImage:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rgba(self) -> bytes: ...

class AudioClip:
    @property
    def name(self) -> str: ...
    @property
    def extension(self) -> str: ...
    @property
    def payload_kind(self) -> str: ...
    @property
    def data(self) -> bytes: ...

class BinaryAsset:
    @property
    def name(self) -> str: ...
    @property
    def extension(self) -> str: ...
    @property
    def payload_kind(self) -> str: ...
    @property
    def data(self) -> bytes: ...

class Material:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def shader(self) -> tuple[int, int]: ...
    @property
    def legacy_shader_keywords(self) -> list[str]: ...
    @property
    def valid_keywords(self) -> list[str]: ...
    @property
    def invalid_keywords(self) -> list[str]: ...
    @property
    def lightmap_flags(self) -> Optional[int]: ...
    @property
    def enable_instancing_variants(self) -> Optional[bool]: ...
    @property
    def custom_render_queue(self) -> Optional[int]: ...
    @property
    def string_tags(self) -> list[tuple[str, str]]: ...
    @property
    def disabled_shader_passes(self) -> list[str]: ...
    @property
    def texture_environments(
        self,
    ) -> list[
        tuple[str, tuple[int, int], tuple[float, float], tuple[float, float]]
    ]: ...
    @property
    def integers(self) -> list[tuple[str, int]]: ...
    @property
    def floats(self) -> list[tuple[str, float]]: ...
    @property
    def colors(self) -> list[tuple[str, tuple[float, float, float, float]]]: ...
    @property
    def trailing_bytes(self) -> int: ...

class MonoScript:
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def execution_order(self) -> Optional[int]: ...
    @property
    def class_name(self) -> str: ...
    @property
    def namespace(self) -> str: ...
    @property
    def assembly_name(self) -> str: ...
    @property
    def is_editor_script(self) -> Optional[bool]: ...

class SceneLimits:
    def __new__(
        cls,
        *,
        maximum_game_objects: int = 1_000_000,
        maximum_total_components: int = 10_000_000,
        maximum_total_transform_child_references: int = 10_000_000,
        maximum_total_material_references: int = 10_000_000,
        maximum_total_bone_references: int = 10_000_000,
        maximum_hierarchy_edges: int = 1_000_000,
        maximum_index_bytes: int = 268_435_456,
    ) -> SceneLimits: ...
    @property
    def maximum_game_objects(self) -> int: ...
    @property
    def maximum_total_components(self) -> int: ...
    @property
    def maximum_total_transform_child_references(self) -> int: ...
    @property
    def maximum_total_material_references(self) -> int: ...
    @property
    def maximum_total_bone_references(self) -> int: ...
    @property
    def maximum_hierarchy_edges(self) -> int: ...
    @property
    def maximum_index_bytes(self) -> int: ...

class ModelTextureLimits:
    def __new__(
        cls,
        *,
        maximum_texture_references: int = 1_000_000,
        maximum_textures: int = 4_096,
        maximum_name_index_bytes: int = 67_108_864,
        maximum_total_encoded_bytes: int = 2_147_483_648,
        maximum_single_texture_bytes: int = 536_870_912,
    ) -> ModelTextureLimits: ...
    @property
    def maximum_texture_references(self) -> int: ...
    @property
    def maximum_textures(self) -> int: ...
    @property
    def maximum_name_index_bytes(self) -> int: ...
    @property
    def maximum_total_encoded_bytes(self) -> int: ...
    @property
    def maximum_single_texture_bytes(self) -> int: ...

class SceneNode:
    @property
    def file_index(self) -> int: ...
    @property
    def path_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def parent(self) -> Optional[tuple[int, int]]: ...
    @property
    def children(self) -> list[tuple[int, int]]: ...
    @property
    def local_position(self) -> Optional[tuple[float, float, float]]: ...
    @property
    def local_rotation(self) -> Optional[tuple[float, float, float, float]]: ...
    @property
    def local_scale(self) -> Optional[tuple[float, float, float]]: ...
    @property
    def mesh(self) -> Optional[tuple[int, int]]: ...
    @property
    def materials(self) -> list[Optional[tuple[int, int]]]: ...
    @property
    def bones(self) -> list[Optional[tuple[int, int]]]: ...
    @property
    def animator(self) -> Optional[tuple[int, int]]: ...

class FbxCandidate:
    @property
    def file_index(self) -> int: ...
    @property
    def path_id(self) -> int: ...
    @property
    def animator(self) -> Optional[tuple[int, int]]: ...
    @property
    def name(self) -> str: ...

class ModelFile:
    @property
    def file_name(self) -> str: ...
    @property
    def data(self) -> bytes: ...

class ModelObj:
    @property
    def obj(self) -> bytes: ...
    @property
    def material_library_name(self) -> str: ...
    @property
    def material_library(self) -> bytes: ...
    @property
    def textures(self) -> list[ModelFile]: ...
    @property
    def skipped(self) -> list[str]:
        """Texture references that could not be resolved or decoded, with the
        reason. Reported rather than raised so one bad texture does not cost
        the model."""

class TexturedFbx:
    @property
    def fbx(self) -> bytes: ...
    @property
    def textures(self) -> list[ModelFile]: ...
    @property
    def skipped(self) -> list[str]: ...

class MonoBehaviourJson:
    @property
    def json(self) -> str: ...
    @property
    def source(self) -> str:
        """``"embedded"`` when the file carried its own type tree, ``"schema"``
        when the layout came from a supplied schema. A value read through a
        schema is only as good as that schema."""

class ExportReport:
    @property
    def exported(self) -> list[str]: ...
    @property
    def failures(self) -> list[str]: ...
    @property
    def unsupported(self) -> list[str]: ...

class ExportLimits:
    def __new__(
        cls,
        *,
        maximum_objects: int = 1_000_000,
        maximum_total_output_bytes: int = 17_179_869_184,
    ) -> ExportLimits: ...
    @property
    def maximum_objects(self) -> int: ...
    @property
    def maximum_total_output_bytes(self) -> int: ...

class ExtractionLimits:
    def __new__(
        cls,
        *,
        maximum_input_files: int = 1_000_000,
        maximum_nesting_depth: int = 32,
        maximum_entries: int = 1_000_000,
        maximum_single_entry_bytes: int = 536_870_912,
        maximum_expanded_bytes: int = 4_294_967_296,
        maximum_output_bytes: int = 4_294_967_296,
        maximum_path_bytes: int = 32_767,
        maximum_total_path_bytes: int = 67_108_864,
    ) -> ExtractionLimits: ...
    @property
    def maximum_input_files(self) -> int: ...
    @property
    def maximum_nesting_depth(self) -> int: ...
    @property
    def maximum_entries(self) -> int: ...
    @property
    def maximum_single_entry_bytes(self) -> int: ...
    @property
    def maximum_expanded_bytes(self) -> int: ...
    @property
    def maximum_output_bytes(self) -> int: ...
    @property
    def maximum_path_bytes(self) -> int: ...
    @property
    def maximum_total_path_bytes(self) -> int: ...

class ExtractionRecord:
    @property
    def source(self) -> str: ...
    @property
    def output_path(self) -> str: ...
    @property
    def bytes(self) -> int: ...

class ExtractionSkip:
    @property
    def source(self) -> str: ...
    @property
    def output_path(self) -> str: ...

class ExtractionFailure:
    @property
    def source(self) -> str: ...
    @property
    def error(self) -> str: ...

class ExtractionReport:
    @property
    def extracted(self) -> list[ExtractionRecord]: ...
    @property
    def skipped_existing(self) -> list[ExtractionSkip]: ...
    @property
    def failures(self) -> list[ExtractionFailure]: ...
    @property
    def output_bytes(self) -> int: ...

class Live2dTexture:
    @property
    def file_name(self) -> str: ...
    @property
    def png(self) -> bytes: ...

class Live2dExpressionFile:
    @property
    def name(self) -> str: ...
    @property
    def file_name(self) -> str: ...
    @property
    def json(self) -> bytes: ...

class Live2dMotionFile:
    @property
    def name(self) -> str: ...
    @property
    def file_name(self) -> str: ...
    @property
    def json(self) -> bytes: ...

class Live2dJsonFile:
    @property
    def file_name(self) -> str: ...
    @property
    def json(self) -> bytes: ...

class Live2dPackage:
    @property
    def model(self) -> tuple[int, int]: ...
    @property
    def moc_object(self) -> tuple[int, int]: ...
    @property
    def name(self) -> str: ...
    @property
    def directory_name(self) -> str: ...
    @property
    def moc_file_name(self) -> str: ...
    @property
    def moc(self) -> bytes: ...
    @property
    def manifest_file_name(self) -> str: ...
    @property
    def manifest(self) -> bytes: ...
    @property
    def textures(self) -> list[Live2dTexture]: ...
    @property
    def expressions(self) -> list[Live2dExpressionFile]: ...
    @property
    def motions(self) -> list[Live2dMotionFile]: ...
    @property
    def eye_blink_parameters(self) -> list[str]: ...
    @property
    def lip_sync_parameters(self) -> list[str]: ...
    @property
    def physics(self) -> Optional[Live2dJsonFile]: ...
    @property
    def pose(self) -> Optional[Live2dJsonFile]: ...
    @property
    def display_info(self) -> Optional[Live2dJsonFile]: ...

class Live2dDiagnostic:
    @property
    def object(self) -> tuple[int, int]: ...
    @property
    def kind(self) -> str: ...
    @property
    def message(self) -> str: ...

class Live2dPackageSet:
    @property
    def packages(self) -> list[Live2dPackage]: ...
    @property
    def diagnostics(self) -> list[Live2dDiagnostic]: ...

class AssetStudio:
    def __new__(
        cls,
        path: Union[str, PathLike[str]],
        *,
        unity_version: Optional[str] = None,
        maximum_input_files: int = 1_000_000,
        maximum_input_directories: int = 1_000_000,
        maximum_directory_entries: int = 2_000_000,
        maximum_path_bytes: int = 1_048_576,
        maximum_total_path_bytes: int = 67_108_864,
        oodle_decoder: Optional[OodleDecoder] = None,
        skip_unreadable_inputs: bool = False,
        unity_cn_key: Union[bytes, str, None] = None,
    ) -> AssetStudio: ...
    @staticmethod
    def from_bytes(
        data: bytes,
        *,
        name: str = "memory.assets",
        unity_version: Optional[str] = None,
        maximum_bytes: int = 4_294_967_296,
        maximum_path_bytes: int = 1_048_576,
        maximum_total_path_bytes: int = 67_108_864,
        oodle_decoder: Optional[OodleDecoder] = None,
    ) -> AssetStudio: ...
    @staticmethod
    def from_memory_files(
        files: list[tuple[str, bytes]],
        *,
        unity_version: Optional[str] = None,
        maximum_files: int = 100_000,
        maximum_file_bytes: int = 536_870_912,
        maximum_total_bytes: int = 4_294_967_296,
        maximum_path_bytes: int = 1_048_576,
        maximum_total_path_bytes: int = 67_108_864,
        oodle_decoder: Optional[OodleDecoder] = None,
        skip_unreadable_inputs: bool = False,
        unity_cn_key: Union[bytes, str, None] = None,
    ) -> AssetStudio: ...
    @property
    def file_count(self) -> int: ...
    @property
    def object_count(self) -> int: ...
    @property
    def resource_count(self) -> int: ...
    def files(self) -> list[FileInfo]: ...
    def objects(self) -> list[ObjectInfo]: ...
    def resources(self) -> list[ResourceInfo]: ...
    def iter_files(self) -> FileIterator: ...
    def iter_objects(self) -> ObjectIterator: ...
    def iter_resources(self) -> ResourceIterator: ...
    def file_page(
        self,
        *,
        offset: int = 0,
        limit: int = 4096,
    ) -> list[FileInfo]: ...
    def object_page(
        self,
        file_index: int,
        *,
        offset: int = 0,
        limit: int = 4096,
    ) -> list[ObjectInfo]: ...
    def resource_page(
        self,
        *,
        offset: int = 0,
        limit: int = 4096,
    ) -> list[ResourceInfo]: ...
    def read_resource(
        self,
        resource_index: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_resource_range(
        self,
        resource_index: int,
        offset: int,
        length: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_resource_by_path(
        self,
        path: str,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def scene(
        self,
        *,
        limits: Optional[SceneLimits] = None,
    ) -> list[SceneNode]: ...
    def read_static_fbx(
        self,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_fbx(
        self,
        *,
        maximum_bytes: int = 536_870_912,
        acl_decoder: Optional[AclDecoder] = None,
    ) -> bytes: ...
    def read_static_fbx_binary(
        self,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_fbx_binary(
        self,
        *,
        maximum_bytes: int = 536_870_912,
        acl_decoder: Optional[AclDecoder] = None,
    ) -> bytes: ...
    def split_object_fbx_candidates(self) -> list[FbxCandidate]: ...
    def animator_fbx_candidates(self) -> list[FbxCandidate]: ...
    def read_game_object_fbx(
        self,
        file_index: int,
        path_id: int,
        *,
        include_animations: bool = True,
        maximum_bytes: int = 536_870_912,
        acl_decoder: Optional[AclDecoder] = None,
    ) -> bytes: ...
    def read_live2d_packages(
        self,
        *,
        schemas: Optional[MonoBehaviourSchemas] = None,
        acl_decoder: Optional[AclDecoder] = None,
        maximum_file_bytes: int = 536_870_912,
        maximum_total_bytes: int = 4_294_967_296,
    ) -> Live2dPackageSet: ...
    def read_raw(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_text(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_shader(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_model_obj(
        self,
        *,
        material_library_name: str = "model.mtl",
        texture_format: str = "png",
        maximum_bytes: int = 536_870_912,
        texture_limits: Optional[ModelTextureLimits] = None,
    ) -> ModelObj: ...
    def read_fbx_with_textures(
        self,
        *,
        texture_format: str = "png",
        maximum_bytes: int = 536_870_912,
        texture_limits: Optional[ModelTextureLimits] = None,
    ) -> TexturedFbx: ...
    def read_mesh_obj(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> bytes: ...
    def read_animation_clip(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> AnimationClip: ...
    def read_legacy_animation(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 268_435_456,
    ) -> LegacyAnimation: ...
    def read_animator_override_controller(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 268_435_456,
    ) -> AnimatorOverrideController: ...
    def read_asset_bundle(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_entries: int = 1_000_000,
        maximum_string_bytes: int = 16_777_216,
        maximum_total_string_bytes: int = 67_108_864,
    ) -> AssetBundle: ...
    def read_resource_manager(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_entries: int = 1_000_000,
        maximum_string_bytes: int = 16_777_216,
        maximum_total_string_bytes: int = 67_108_864,
    ) -> ResourceManager: ...
    def read_preload_data(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_entries: int = 1_000_000,
    ) -> PreloadData: ...
    def inspect_acl_tracks(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
        maximum_decompressed_values: int = 134_217_728,
    ) -> AclCompressedTracks: ...
    def read_acl_decoder_input(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
        maximum_decoder_map_entries: int = 2_000_000,
        maximum_materialized_bytes: int = 536_870_912,
    ) -> tuple[bytes, list[int]]: ...
    def decode_acl_tracks(
        self,
        file_index: int,
        path_id: int,
        decoder: AclDecoder,
        *,
        maximum_bytes: int = 536_870_912,
        maximum_values: int = 134_217_728,
    ) -> AclDecodedClip: ...
    def read_animator_controller(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> AnimatorController: ...
    def read_avatar(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> Avatar: ...
    def read_type_tree_json(
        self,
        file_index: int,
        path_id: int,
        *,
        pretty: bool = False,
        maximum_bytes: int = 268_435_456,
    ) -> str: ...
    def read_type_tree_dump(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 268_435_456,
    ) -> str: ...
    def read_mono_behaviour_json(
        self,
        file_index: int,
        path_id: int,
        schema: MonoBehaviourSchema,
        *,
        pretty: bool = False,
        maximum_bytes: int = 268_435_456,
    ) -> MonoBehaviourJson: ...
    def read_mono_behaviour_json_with_schemas(
        self,
        file_index: int,
        path_id: int,
        schemas: MonoBehaviourSchemas,
        *,
        pretty: bool = False,
        maximum_bytes: int = 268_435_456,
    ) -> MonoBehaviourJson: ...
    def read_texture(
        self,
        file_index: int,
        path_id: int,
        *,
        mip_level: int = 0,
        maximum_bytes: int = 536_870_912,
    ) -> RgbaImage: ...
    def read_texture_array(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> list[RgbaImage]: ...
    def read_sprite_atlas(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_entries: int = 1_000_000,
        maximum_string_bytes: int = 16_777_216,
        maximum_total_string_bytes: int = 33_554_432,
    ) -> SpriteAtlas: ...
    def read_sprite_metadata(
        self,
        file_index: int,
        path_id: int,
        *,
        limits: Optional[SpriteMetadataLimits] = None,
    ) -> SpriteMetadata: ...
    def read_sprite(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> RgbaImage: ...
    def read_audio_clip(
        self,
        file_index: int,
        path_id: int,
        *,
        format: str = "auto",
        maximum_bytes: int = 536_870_912,
    ) -> AudioClip: ...
    def read_font(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> BinaryAsset: ...
    def read_movie_texture(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> BinaryAsset: ...
    def read_video_clip(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_bytes: int = 536_870_912,
    ) -> BinaryAsset: ...
    def read_material(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_object_bytes: int = 268_435_456,
        maximum_string_bytes: int = 16_777_216,
        maximum_array_elements: int = 1_000_000,
    ) -> Material: ...
    def read_mono_script(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_string_bytes: int = 16_777_216,
    ) -> MonoScript: ...
    def read_build_settings(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_string_bytes: int = 16_777_216,
        maximum_paths: int = 1_000_000,
    ) -> BuildSettings: ...
    def read_player_settings(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_string_bytes: int = 16_777_216,
    ) -> PlayerSettings: ...
    def read_cubism_expression(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_parameters: int = 1_000_000,
        maximum_string_bytes: int = 16_777_216,
        maximum_output_bytes: int = 268_435_456,
    ) -> CubismExpression: ...
    def read_cubism_pose_part(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_links: int = 1_000_000,
        maximum_string_bytes: int = 16_777_216,
    ) -> CubismPosePart: ...
    def read_cubism_display_info(
        self,
        file_index: int,
        path_id: int,
        *,
        maximum_string_bytes: int = 16_777_216,
    ) -> CubismDisplayInfo: ...
    def read_cubism_physics(
        self,
        file_index: int,
        path_id: int,
        *,
        motion_fps: float = 0.0,
        maximum_elements: int = 1_000_000,
        maximum_output_bytes: int = 268_435_456,
    ) -> CubismPhysics: ...
    def read_cubism_fade_motion(
        self,
        file_index: int,
        path_id: int,
        *,
        force_bezier: bool = False,
        maximum_curves: int = 1_000_000,
        maximum_output_bytes: int = 268_435_456,
    ) -> CubismFadeMotion: ...
    def read_cubism_clip_motion(
        self,
        file_index: int,
        path_id: int,
        *,
        targets: Optional[CubismMotionTargets] = None,
        force_bezier: bool = False,
        maximum_output_bytes: int = 268_435_456,
    ) -> CubismClipMotion: ...
    def read_cubism_acl_clip_motion(
        self,
        file_index: int,
        path_id: int,
        decoder: AclDecoder,
        *,
        targets: Optional[CubismMotionTargets] = None,
        maximum_output_bytes: int = 268_435_456,
    ) -> CubismClipMotion: ...
    def export(
        self,
        output: Union[str, PathLike[str]],
        *,
        mode: str = "auto",
        image_format: str = "png",
        jpeg_quality: int = 75,
        overwrite: bool = False,
        limits: Optional[ExportLimits] = None,
    ) -> ExportReport: ...

def extract(
    input: Union[str, PathLike[str]],
    output: Union[str, PathLike[str]],
    *,
    overwrite: bool = False,
    limits: Optional[ExtractionLimits] = None,
    oodle_decoder: Optional[OodleDecoder] = None,
    unity_cn_key: Union[bytes, str, None] = None,
) -> ExtractionReport: ...
