#!/usr/bin/env python3
"""Emits the real TypeTree node lists the pre-13 oracle fixtures embed.

Serialized formats 5 through 12 always carry a TypeTree; unlike 13 and later
there is no flag that turns it off. The differential oracle could therefore only
cover 13 through 21, because a fixture for the older formats has to embed a tree
and inventing one would prove nothing: the gate would compare two readers
against a shape Unity never wrote.

This script reads the trees from UnityPy's bundled `lzma.tpk` and writes them as
JSON for the Rust test to assemble into files. The TPK itself is *not* vendored
here and this script does not run in CI: it is a one-off development tool, and
its JSON output is what the repository keeps.

Provenance, since the output is committed:

    UnityPy (MIT) ships `resources/lzma.tpk`, which is generated from
    AssetRipper's TypeTreeDumps (GPL-3.0 parent lineage). Only the node values
    for one class at a handful of Unity versions are extracted, which is
    interface data describing Unity's own serialization layout rather than any
    part of either project's implementation.

Usage, from the repository root, with UnityPy installed:

    python3 tools/generate_typetree_fixtures.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from UnityPy.helpers import Tpk
from UnityPy.helpers.UnityVersion import UnityVersion

TEXT_ASSET_CLASS_ID = 49

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "crates"
    / "unity-rs-core"
    / "tests"
    / "fixtures"
    / "typetree"
    / "text_asset.json"
)

# One Unity version per serialized format that needs a tree, chosen as the
# release that actually wrote that format.
#
# Formats 5 and 6 predate the Unity version string in the file, so a reader has
# nothing to key on and assumes 2.5.0. The TPK's earliest exact entry is 3.4, so
# those two reuse it; TextAsset's layout is identical across the whole range,
# which the generated JSON makes checkable rather than assumed.
FORMAT_VERSIONS = {
    5: "3.4.0f5",
    6: "3.4.0f5",
    7: "3.4.0f5",
    8: "3.5.0f5",
    9: "4.0.0f7",
    10: "4.2.0f4",
    11: "4.5.0f6",
    12: "4.6.0f3",
}


def flatten(node: Any, out: list[dict[str, Any]]) -> None:
    """Appends `node` and its descendants in serialized (depth-first) order."""
    out.append(
        {
            "type": node.m_Type,
            "name": node.m_Name,
            "byte_size": node.m_ByteSize,
            "index": node.m_Index,
            # The TPK carries no value here: `m_TypeFlags` is the field added in
            # format 19, while the same slot in a pre-13 tree is Unity's older
            # `isArray` int. It is exactly the array-ness of the node, so it is
            # derived rather than guessed.
            "is_array": 1 if node.m_Type == "Array" else 0,
            "version": node.m_Version,
            "meta_flags": node.m_MetaFlag,
            "level": node.m_Level,
            "children": len(node.m_Children),
        }
    )
    for child in node.m_Children:
        flatten(child, out)


def main() -> None:
    trees: dict[str, Any] = {}
    for format_version, unity_version in sorted(FORMAT_VERSIONS.items()):
        root = Tpk.get_typetree_node(
            TEXT_ASSET_CLASS_ID, UnityVersion.from_str(unity_version)
        )
        nodes: list[dict[str, Any]] = []
        flatten(root, nodes)
        trees[str(format_version)] = {"unity_version": unity_version, "nodes": nodes}

    document = {
        "_comment": (
            "Generated by tools/generate_typetree_fixtures.py from UnityPy's "
            "bundled lzma.tpk, which is itself generated from AssetRipper's "
            "TypeTreeDumps. These are Unity's own serialization layouts for "
            "TextAsset, extracted so the differential oracle can cover "
            "serialized formats 5 through 12, which always carry a tree. Do not "
            "hand-edit: regenerate instead."
        ),
        "class_id": TEXT_ASSET_CLASS_ID,
        "trees": trees,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} for formats {sorted(FORMAT_VERSIONS)}")


if __name__ == "__main__":
    main()
