#!/usr/bin/env python3
"""Generate the locked workspace's complete third-party license bundle.

Cargo packages normally ship their license documents in the registry source
archive. Native CLI, Python and Node distributions statically incorporate
those packages, so those binary artifacts must carry the texts as well. This
script follows the non-development dependency graph of every shipped workspace
package and produces one deterministic aggregate file.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
SHIPPED_PACKAGES = (
    "assetstudio-core",
    "assetstudio-cli",
    "assetstudio-python",
    "assetstudio-node",
)
PACKAGE_DIRECTORIES = (
    ROOT / "crates" / "assetstudio-core",
    ROOT / "crates" / "assetstudio-node",
    ROOT / "crates" / "assetstudio-python" / "python" / "assetstudio",
)
GENERATED_LICENSE_OUTPUTS = (ROOT / "THIRD_PARTY_LICENSES.txt",) + tuple(
    directory / "THIRD_PARTY_LICENSES.txt" for directory in PACKAGE_DIRECTORIES
)
SYNCED_LEGAL_FILES = ("LICENSE", "THIRD_PARTY_NOTICES.md")
LEGAL_PREFIXES = (
    "LICENSE",
    "LICENCE",
    "COPYING",
    "COPYRIGHT",
    "NOTICE",
    "UNLICENSE",
    "AUTHORS",
)
FALLBACKS = {
    ("alloc-stdlib", "0.2.4"): (
        ROOT / "tools" / "legal-fallbacks" / "alloc-stdlib-0.2.4-LICENSE",
    ),
    ("napi", "3.12.1"): (
        ROOT / "tools" / "legal-fallbacks" / "napi-rs-LICENSE",
    ),
    ("napi-build", "2.4.1"): (
        ROOT / "tools" / "legal-fallbacks" / "napi-rs-LICENSE",
    ),
    ("napi-derive", "3.6.3"): (
        ROOT / "tools" / "legal-fallbacks" / "napi-rs-LICENSE",
    ),
    ("napi-derive-backend", "6.1.2"): (
        ROOT / "tools" / "legal-fallbacks" / "napi-rs-LICENSE",
    ),
    ("napi-sys", "3.3.0"): (
        ROOT / "tools" / "legal-fallbacks" / "napi-rs-LICENSE",
    ),
}


def cargo_metadata() -> dict[str, Any]:
    output = subprocess.check_output(
        ["cargo", "metadata", "--locked", "--format-version", "1"],
        cwd=ROOT,
    )
    return json.loads(output)


def shipped_dependency_ids(metadata: dict[str, Any]) -> set[str]:
    workspace = set(metadata["workspace_members"])
    packages = {package["id"]: package for package in metadata["packages"]}
    roots = {
        package["name"]: package["id"]
        for package in metadata["packages"]
        if package["id"] in workspace
    }
    missing = sorted(set(SHIPPED_PACKAGES) - roots.keys())
    if missing:
        raise RuntimeError(f"workspace is missing shipped packages: {missing}")

    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    seen: set[str] = set()
    pending = [roots[name] for name in SHIPPED_PACKAGES]
    while pending:
        package_id = pending.pop()
        if package_id in seen:
            continue
        seen.add(package_id)
        for dependency in nodes[package_id].get("deps", []):
            dependency_kinds = dependency.get("dep_kinds", [])
            if not dependency_kinds or any(
                item.get("kind") != "dev" for item in dependency_kinds
            ):
                pending.append(dependency["pkg"])
    return seen - workspace


def license_files(package: dict[str, Any]) -> tuple[Path, ...]:
    package_dir = Path(package["manifest_path"]).parent
    candidates: list[Path] = []
    declared = package.get("license_file")
    if declared:
        declared_path = Path(declared)
        candidates.append(
            declared_path if declared_path.is_absolute() else package_dir / declared_path
        )
    candidates.extend(
        path
        for path in package_dir.iterdir()
        if path.is_file() and path.name.upper().startswith(LEGAL_PREFIXES)
    )
    unique = tuple(sorted({path.resolve() for path in candidates if path.is_file()}))
    if unique:
        return unique

    fallback = FALLBACKS.get((package["name"], package["version"]))
    if fallback and all(path.is_file() for path in fallback):
        return tuple(path.resolve() for path in fallback)
    raise RuntimeError(
        "dependency has no distributable license file and no reviewed fallback: "
        f"{package['name']} {package['version']} ({package.get('license')})"
    )


def render_bundle(metadata: dict[str, Any]) -> bytes:
    packages = {package["id"]: package for package in metadata["packages"]}
    dependencies = sorted(
        (packages[package_id] for package_id in shipped_dependency_ids(metadata)),
        key=lambda package: (
            package["name"],
            package["version"],
            package.get("source") or "",
        ),
    )
    lines = [
        "unity-rs workspace - third-party license texts\n",
        "\n",
        "Generated by tools/generate_dependency_licenses.py from Cargo.lock and ",
        "cargo metadata. Development-only dependencies are excluded. The bundle ",
        "is a conservative union for the shipped Core, CLI, Python and Node ",
        "packages.\n",
    ]
    for package in dependencies:
        files = license_files(package)
        lines.extend(
            [
                "\n",
                "=" * 78 + "\n",
                f"Package: {package['name']} {package['version']}\n",
                f"License expression: {package.get('license') or 'not declared'}\n",
                f"Repository: {package.get('repository') or 'not declared'}\n",
            ]
        )
        for path in files:
            try:
                contents = path.read_text(encoding="utf-8")
            except UnicodeDecodeError as error:
                raise RuntimeError(f"license file is not UTF-8 text: {path}") from error
            lines.extend(
                [
                    "\n",
                    f"--- {path.name} ---\n",
                    contents,
                    "" if contents.endswith("\n") else "\n",
                ]
            )
    return "".join(lines).encode("utf-8")


def write_outputs(expected: bytes) -> None:
    for output in GENERATED_LICENSE_OUTPUTS:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(expected)
        print(f"wrote {output.relative_to(ROOT)}")
    for name in SYNCED_LEGAL_FILES:
        source = ROOT / name
        if not source.is_file():
            raise RuntimeError(f"missing root legal document: {name}")
        contents = source.read_bytes()
        for directory in PACKAGE_DIRECTORIES:
            output = directory / name
            output.write_bytes(contents)
            print(f"wrote {output.relative_to(ROOT)}")


def check_outputs(expected: bytes) -> None:
    failures = []
    for output in GENERATED_LICENSE_OUTPUTS:
        if not output.is_file():
            failures.append(f"missing {output.relative_to(ROOT)}")
        elif output.read_bytes() != expected:
            failures.append(f"stale {output.relative_to(ROOT)}")
    for name in SYNCED_LEGAL_FILES:
        source = ROOT / name
        if not source.is_file():
            failures.append(f"missing {name}")
            continue
        expected_copy = source.read_bytes()
        for directory in PACKAGE_DIRECTORIES:
            output = directory / name
            if not output.is_file():
                failures.append(f"missing {output.relative_to(ROOT)}")
            elif output.read_bytes() != expected_copy:
                failures.append(f"stale {output.relative_to(ROOT)}")
    if failures:
        raise RuntimeError("; ".join(failures))
    print(
        "legal documents: dependency bundle and package copies are synchronized"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render_bundle(cargo_metadata())
    if args.write:
        write_outputs(expected)
    else:
        check_outputs(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
