/* auto-generated by NAPI-RS */
/* eslint-disable */
/** One opened collection. All format work is delegated to `unity-rs-core`. */
export declare class UnityRs {
  constructor(path: string)
  /**
   * Opens a path, parsing against `unityVersion` instead of the version the
   * files declare.
   *
   * Needed for files whose own version was stripped at build time, where a
   * reader has nothing to key its layout decisions on.
   */
  static openWithVersion(path: string, unityVersion: string): UnityRs
  /**
   * Writes the animated FBX, decoding ACL tracks through a caller-supplied
   * decoder.
   *
   * Core ships no ACL decoder. Without one a clip whose samples are ACL
   * compressed contributes nothing to the FBX; with one its tracks are
   * validated on the way back in -- shape, ordering and budgets are Core's
   * checks, not the caller's promises.
   *
   * Asynchronous for the same reason as the Oodle entry point: the callback
   * runs on the event loop while a worker waits for it.
   */
  readFbxWithAclDecoder(decoder: (request: AclDecodeRequest) => AclDecodedClip, maximumBytes?: number | undefined | null): Promise<Buffer>
  /**
   * Writes the animated scene as binary FBX 7.4, decoding ACL tracks
   * through a caller-supplied decoder on a worker.
   */
  readFbxBinaryWithAclDecoder(decoder: (request: AclDecodeRequest) => AclDecodedClip, maximumBytes?: number | undefined | null): Promise<Buffer>
  /**
   * Opens a path with any combination of the load options.
   *
   * The single-option factories remain for the cases they already cover;
   * this is the one that can express two facts about the same file.
   */
  static openWith(path: string, options?: OpenOptions | undefined | null): UnityRs
  /**
   * Opens a path whose bundles are Oodle-compressed, using a
   * caller-supplied decoder.
   *
   * Asynchronous by necessity, not for convenience: the decoder runs on the
   * JavaScript event loop while a worker waits for it, so calling this
   * synchronously would block the loop that has to run the callback.
   *
   * The callback receives the compressed bytes and the exact expected output
   * length, and must return precisely that many bytes.
   */
  static openWithOodle(path: string, decoder: (input: Buffer, expectedLength: number) => Buffer, options?: OpenOptions | undefined | null): Promise<UnityRs>
  /**
   * Opens a path on a libuv worker so container discovery does not block
   * the JavaScript event loop. The optional settings are identical to
   * `openWith`; existing one-argument calls remain valid.
   */
  static openAsync(path: string, options?: OpenOptions | undefined | null): Promise<UnityRs>
  /**
   * Opens one in-memory asset, bundle, or resource after copying the Node
   * buffer into Rust-owned immutable storage.
   *
   * The final options argument exposes the same version override, UnityCN
   * key, failure policy, and discovery budgets as `openWith`. It is last so
   * existing `(data, name, maximumBytes)` calls remain source-compatible.
   */
  static fromBuffer(data: Uint8Array, name?: string | undefined | null, maximumBytes?: number | undefined | null, options?: OpenOptions | undefined | null): UnityRs
  /**
   * Copies a Node buffer once, then parses it on a libuv worker. The final
   * options argument matches the synchronous `fromBuffer` entry point.
   */
  static fromBufferAsync(data: Uint8Array, name?: string | undefined | null, maximumBytes?: number | undefined | null, options?: OpenOptions | undefined | null): Promise<UnityRs>
  get fileCount(): number
  get objectCount(): number
  get resourceCount(): number
  get loadDiagnosticCount(): number
  loadDiagnosticPage(offset?: number | undefined | null, limit?: number | undefined | null): Array<LoadDiagnosticInfo>
  filePage(offset?: number | undefined | null, limit?: number | undefined | null): Array<FileInfo>
  objectPage(fileIndex: number, offset?: number | undefined | null, limit?: number | undefined | null): Array<ObjectInfo>
  resourcePage(offset?: number | undefined | null, limit?: number | undefined | null): Array<ResourceInfo>
  readResource(resourceIndex: number, maximumBytes?: number | undefined | null): Buffer
  readRaw(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readRawAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readText(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readTextAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTypeTreeJson(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Buffer
  readTypeTreeJsonAsync(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTypeTreeDump(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readTypeTreeDumpAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readShader(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readShaderAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readMeshObj(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Buffer
  readMeshObjAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Buffer>
  readTexture(fileIndex: number, pathId: bigint, mipLevel?: number | undefined | null, maximumBytes?: number | undefined | null): RgbaImage
  readTextureAsync(fileIndex: number, pathId: bigint, mipLevel?: number | undefined | null, maximumBytes?: number | undefined | null): Promise<RgbaImage>
  readTextureArray(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Array<RgbaImage>
  readTextureArrayAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<Array<RgbaImage>>
  /** Reads one complete, bounded Unity `SpriteAtlas` metadata table. */
  readSpriteAtlas(fileIndex: number, pathId: bigint, maximumEntries?: number | undefined | null, maximumStringBytes?: number | undefined | null, maximumTotalStringBytes?: number | undefined | null): SpriteAtlasInfo
  /**
   * Reads one complete, bounded Unity `Sprite` metadata object without
   * resolving or decoding its texture references.
   */
  readSpriteMetadata(fileIndex: number, pathId: bigint, limits?: SpriteMetadataLimits | undefined | null): SpriteMetadata
  readSprite(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): RgbaImage
  readSpriteAsync(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Promise<RgbaImage>
  /**
   * Encodes one decoded RGBA image into a complete file payload using the
   * same bounded Core encoders as `exportWithOptions`: `png` (the
   * default), `jpeg`, `bmp`, `tga`, `webp`, or `raw-rgba`.
   *
   * The pixels must be display-order rows exactly as `readTexture`,
   * `readTextureArray`, and `readSprite` return them.
   */
  static encodeImage(image: RgbaImage, options?: EncodeImageOptions | undefined | null): Buffer
  /**
   * The worker-thread variant of `encodeImage` for pipelines that keep
   * pixel-proportional encoding off the event loop.
   */
  static encodeImageAsync(image: RgbaImage, options?: EncodeImageOptions | undefined | null): Promise<Buffer>
  /** Reads an `AudioClip`'s stored payload without transcoding it. */
  readAudio(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AudioClip
  /**
   * Reads an `AudioClip` using the same `auto`, `raw`, or `wav` policy as
   * Core, Python and the CLI exporter.
   *
   * `auto` writes a WAV only when Core has verified a decoder-free path;
   * otherwise it preserves the source container. `wav` requires such a
   * path and refuses compressed codecs rather than returning mislabeled
   * bytes. The older `readAudio` method remains a raw-only compatibility
   * alias.
   */
  readAudioClip(fileIndex: number, pathId: bigint, format?: string | undefined | null, maximumBytes?: number | undefined | null): AudioClip
  /** Reads the identity of a `MonoScript`. */
  readMonoScript(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): MonoScript
  /**
   * Reads a `Material`'s shader reference and the names of its properties.
   *
   * Property values are deliberately not flattened here: they are typed
   * per sheet and a caller that needs them is better served by the Rust or
   * Python API than by a lossy JavaScript projection.
   */
  readMaterial(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Material
  /** Reads the scene list a `BuildSettings` object records. */
  readBuildSettings(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BuildSettings
  /** Reads the company and product names from a `PlayerSettings` object. */
  readPlayerSettings(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): PlayerSettings
  /**
   * Reads complete stable skeleton, TOS, and human-description metadata
   * from one bounded `Avatar`.
   */
  readAvatar(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): Avatar
  /**
   * Opens several in-memory inputs as one collection.
   *
   * A serialized file and the `.resS` its textures and audio stream from are
   * separate files; opening them one at a time leaves every streamed payload
   * unresolvable, so a caller holding both in memory needs to pass them
   * together. The final options argument matches `openWith` and is placed
   * after the existing aggregate byte limit to preserve old calls.
   */
  static fromBuffers(inputs: Array<MemoryInput>, maximumBytes?: number | undefined | null, options?: OpenOptions | undefined | null): UnityRs
  /**
   * Reads one checked byte range of a resource without materializing the
   * rest, which is how a caller pulls a single texture out of a large
   * `.resS`.
   */
  readResourceRange(resourceIndex: number, offset: bigint, length: bigint, maximumBytes?: number | undefined | null): Buffer
  /** Finds a resource by the path a serialized file references it through. */
  resourceIndexByPath(path: string): number | null
  /** Assembles the `GameObject` hierarchy across every loaded file. */
  scene(maximumGameObjects?: number | undefined | null): Array<SceneNode>
  /**
   * Assembles the same hierarchy with all collection-wide budgets exposed.
   *
   * `scene(maximumGameObjects)` remains available for compatibility; this
   * method adds component, child, material, bone, and hierarchy-edge limits.
   */
  sceneWithLimits(limits?: SceneLimits | undefined | null): Array<SceneNode>
  /**
   * Writes the whole collection as static ASCII FBX 7.4.
   *
   * Ordinary and skinned renderer geometry, direct and hash-recovered bones
   * and static blend shapes. Animation and textures are separate concerns
   * and are not included.
   */
  readStaticFbx(maximumBytes?: number | undefined | null): Buffer
  /**
   * The same static scene in FBX 7.4's binary encoding.
   *
   * Some importers accept only the binary form, and it is smaller and faster
   * to parse. The scene is identical to `readStaticFbx`.
   */
  readStaticFbxBinary(maximumBytes?: number | undefined | null): Buffer
  /**
   * Reads a `CubismPhysicsController` and writes its physics3.json.
   *
   * `motionFps` is the fallback the converter uses when the rig carries no
   * frame rate of its own, matching the managed extractor's argument.
   */
  readCubismPhysics(fileIndex: number, pathId: bigint, motionFps?: number | undefined | null, maximumBytes?: number | undefined | null): CubismDocument
  /** Reads a `CubismExpressionData` and writes its exp3.json. */
  readCubismExpression(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): CubismDocument
  /** Reads a `CubismFadeMotionData` and writes its motion3.json. */
  readCubismFadeMotion(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): CubismDocument
  /** Reads one embedded-schema `CubismPosePart` component. */
  readCubismPosePart(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): CubismPosePart
  /** Reads one embedded-schema Cubism display-info component. */
  readCubismDisplayInfo(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): CubismDisplayInfo
  /** Projects one real Unity `AnimationClip` to Cubism motion3 JSON. */
  readCubismClipMotion(fileIndex: number, pathId: bigint, targets?: CubismMotionTargets | undefined | null, forceBezier?: boolean | undefined | null, maximumBytes?: number | undefined | null): CubismClipMotion
  /**
   * Projects one ACL-backed Tuanjie `AnimationClip` on a worker.
   *
   * The JavaScript decoder receives only Core-validated, owned ACL input.
   * Core then validates every returned time, binding index and value before
   * the motion3 document is built. The worker is required so the callback
   * can execute on the JavaScript event loop without deadlocking it.
   */
  readCubismClipMotionWithAclDecoder(fileIndex: number, pathId: bigint, decoder: (request: AclDecodeRequest) => AclDecodedClip, targets?: CubismMotionTargets | undefined | null, forceBezier?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<CubismClipMotion>
  /**
   * Enumerates the `GameObject` branches a split-objects export would write.
   *
   * The whole-collection FBX calls put every model in one file; these name
   * the branches so a caller can write one file each, which is what the
   * CLI's `split-objects` does.
   */
  splitObjectFbxCandidates(): Array<FbxCandidate>
  /** Enumerates the branches an Animator owns. */
  animatorFbxCandidates(): Array<FbxCandidate>
  /** Writes one selected `GameObject` branch as FBX. */
  readGameObjectFbx(fileIndex: number, pathId: bigint, includeAnimations?: boolean | undefined | null, maximumBytes?: number | undefined | null): Buffer
  /**
   * Writes one selected `GameObject` branch as animated ASCII FBX while a
   * worker delegates Tuanjie ACL decompression to JavaScript.
   */
  readGameObjectFbxWithAclDecoder(fileIndex: number, pathId: bigint, decoder: (request: AclDecodeRequest) => AclDecodedClip, includeAnimations?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<Buffer>
  /** Reads a `Font`'s resident payload. */
  readFont(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BinaryAsset
  /** Reads the resident Ogg payload from a legacy `MovieTexture`. */
  readMovieTexture(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BinaryAsset
  /** Reads a `VideoClip`'s resident or external payload. */
  readVideoClip(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): BinaryAsset
  /**
   * Exports every supported object into `outputRoot`.
   *
   * The Core exporter writes atomically and never overwrites unless asked,
   * and a failure on one object is recorded rather than raised so a single
   * unreadable asset does not cost the run.
   */
  export(outputRoot: string, overwrite?: boolean | undefined | null): ExportReport
  /**
   * Exports every supported object with the complete Core policy surface.
   *
   * This is additive to `export`: existing callers keep the compact
   * overwrite flag, while callers that need deterministic names, raw/dump
   * modes, image/audio selection or aggregate budgets can express them
   * without dropping to the CLI.
   */
  exportWithOptions(outputRoot: string, options?: ExportConfiguration | undefined | null): ExportReport
  /**
   * Recursively extracts one file or directory tree without loading it.
   *
   * Child symlinks are never followed and every archive path is made
   * relative before it is joined to the output root, so a hostile entry
   * cannot escape it.
   */
  static extract(input: string, outputRoot: string, overwrite?: boolean | undefined | null): ExtractionReport
  /**
   * Reads complete bounded `AnimationClip` shape, muscle, ACL, and external
   * streaming metadata without copying parsed keyframe arrays into
   * JavaScript.
   */
  readAnimationClipInfo(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AnimationClipInfo
  /** Reads the stable references from one legacy Unity `Animation` component. */
  readLegacyAnimation(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): LegacyAnimationInfo
  /** Reads one bounded Unity `AnimatorOverrideController` substitution table. */
  readAnimatorOverrideController(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AnimatorOverrideControllerInfo
  /**
   * Reads inherited/effective names, dependencies and ordered tables from
   * one bounded Unity `AssetBundle` object.
   */
  readAssetBundle(fileIndex: number, pathId: bigint, maximumEntries?: number | undefined | null, maximumStringBytes?: number | undefined | null, maximumTotalStringBytes?: number | undefined | null): AssetBundleInfo
  /** Reads one bounded Unity `ResourceManager` named-container table. */
  readResourceManager(fileIndex: number, pathId: bigint, maximumEntries?: number | undefined | null, maximumStringBytes?: number | undefined | null, maximumTotalStringBytes?: number | undefined | null): ResourceManagerInfo
  /** Reads one bounded Unity `PreloadData` object-reference table. */
  readPreloadData(fileIndex: number, pathId: bigint, maximumEntries?: number | undefined | null, maximumStringBytes?: number | undefined | null, maximumTotalStringBytes?: number | undefined | null): PreloadDataInfo
  /** Reads an `AnimatorController`'s identity and the clips it references. */
  readAnimatorController(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AnimatorControllerInfo
  /**
   * Discovers the Live2D models in the collection.
   *
   * Only the shape of each package is returned. Materializing the files --
   * the MOC, textures and JSON -- is a separate concern and belongs behind
   * an explicit output budget.
   */
  live2DPackages(): Array<Live2DPackageInfo>
  /**
   * Writes the collection as ASCII FBX 7.4 including its animation tracks.
   *
   * The static variant omits animation deliberately; this is the one a
   * caller wants for a rigged model.
   */
  readFbx(maximumBytes?: number | undefined | null): Buffer
  /** The same animated scene in FBX 7.4's binary encoding. */
  readFbxBinary(maximumBytes?: number | undefined | null): Buffer
  /**
   * Materializes every Live2D package: the MOC, the model3 manifest, the
   * mip-zero texture PNGs, and the expression, motion, physics, pose and
   * display-info JSON where their verified fields are present.
   *
   * Returned in memory rather than written, so the caller decides where the
   * files land and stays inside whatever budget it set.
   */
  readLive2DPackages(maximumBytes?: number | undefined | null): Live2DPackageSet
  /**
   * Materializes every verified Live2D package using trusted external
   * MonoBehaviour schemas when a shipped build stripped its type trees.
   *
   * Schemas are inert data produced by an offline tool. Embedded type trees
   * retain priority, matching the Core and Python surfaces.
   */
  readLive2DPackagesWithSchemas(schemas: Array<MonoBehaviourSchema>, maximumFileBytes?: number | undefined | null, maximumTotalBytes?: number | undefined | null): Live2DPackageSet
  /**
   * Materializes every verified Live2D package on a worker while a
   * JavaScript callback decodes Tuanjie ACL animation tracks.
   *
   * `schemas` is optional so the same call handles embedded trees, stripped
   * managed layouts, or both. Core validates all decoded curves and output
   * budgets before JavaScript receives the package bytes.
   */
  readLive2DPackagesWithAclDecoder(decoder: (request: AclDecodeRequest) => AclDecodedClip, schemas?: Array<MonoBehaviourSchema> | undefined | null, maximumFileBytes?: number | undefined | null, maximumTotalBytes?: number | undefined | null): Promise<Live2DPackageSet>
  /**
   * Writes the whole scene as one Wavefront OBJ, with the material library
   * it names and that library's textures.
   *
   * Distinct from `readMeshObj`, which writes one mesh the way the managed
   * exporter does. This is the scene: every renderer placed in world space.
   *
   * `materialLibraryName` is what the OBJ's `mtllib` line will say, so it
   * has to be the name the library is actually written under.
   * `textureFormat` defaults to PNG and accepts the same format names as
   * the Core and Python surfaces. `textureLimits` independently bounds the
   * texture count, total encoded bytes and each texture's payload, decoded
   * output and decoder workspace.
   */
  readModelObj(materialLibraryName?: string | undefined | null, maximumBytes?: number | undefined | null, textureFormat?: string | undefined | null, textureLimits?: ModelTextureLimits | undefined | null): ModelObj
  /**
   * Writes the collection as ASCII FBX with its animations and returns the
   * material textures it references.
   *
   * The FBX names each texture by file name, so the returned files have to
   * be written beside it for those references to resolve. They come back
   * rather than being written because this call has no directory of its own
   * and where they land is the caller's decision. `textureFormat` defaults
   * to PNG and accepts the same format names as the Core and Python surfaces.
   * `textureLimits` has the same meaning as on `readModelObj`.
   */
  readFbxWithTextures(maximumBytes?: number | undefined | null, textureFormat?: string | undefined | null, textureLimits?: ModelTextureLimits | undefined | null): TexturedFbx
  /**
   * Inspects an `AnimationClip`'s ACL blob without decompressing it.
   *
   * Core ships no ACL decoder, so this is what a caller needs to decide
   * whether its own decoder can handle the blob before asking for it.
   */
  readAclTracks(fileIndex: number, pathId: bigint, maximumBytes?: number | undefined | null): AclTracks
  /**
   * Reads a `MonoBehaviour` as JSON through the type tree embedded in the
   * serialized file.
   *
   * A stripped build has no embedded managed layout and is refused rather
   * than guessed; use `readMonoBehaviourJsonWithSchemas` for that case.
   */
  readMonoBehaviourJson(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): MonoBehaviourJson
  /**
   * Worker-backed form of `readMonoBehaviourJson` for large or untrusted
   * embedded type trees.
   */
  readMonoBehaviourJsonAsync(fileIndex: number, pathId: bigint, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<MonoBehaviourJson>
  /**
   * Reads a `MonoBehaviour` as JSON, resolving its stripped managed fields
   * through caller-supplied schemas.
   *
   * A shipped build strips the managed type layout, so without a schema only
   * the engine-owned prefix can be read. The schemas are data: they are
   * matched by assembly, namespace, class and optionally Unity version, and
   * nothing in them is executed.
   */
  readMonoBehaviourJsonWithSchemas(fileIndex: number, pathId: bigint, schemas: Array<MonoBehaviourSchema>, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): MonoBehaviourJson
  /**
   * Worker-backed form of `readMonoBehaviourJsonWithSchemas`. JavaScript
   * values are count-checked and copied before the task is queued; schema
   * identity validation, registry indexing, parsing and JSON
   * materialization happen on the worker.
   */
  readMonoBehaviourJsonWithSchemasAsync(fileIndex: number, pathId: bigint, schemas: Array<MonoBehaviourSchema>, pretty?: boolean | undefined | null, maximumBytes?: number | undefined | null): Promise<MonoBehaviourJson>
}

/**
 * Frame-major scalar curves an injected ACL decoder returns.
 *
 * `bindingIndices[column]` is the absolute Unity binding scalar index for
 * `values[frame * bindingIndices.length + column]`, and the indices must be
 * strictly increasing.
 */
export interface AclDecodedClip {
  times: Array<number>
  bindingIndices: Array<number>
  values: Array<number>
  /** Binding offset for the ordinary streamed curves that follow. */
  followingCurveOffset: number
}

/** What an injected ACL decoder is asked to decode. */
export interface AclDecodeRequest {
  frameCount: number
  boneCount: number
  sampleRate: number
  declaredCurveCount?: number
  useFastSampleMode?: boolean
  /** The validated compressed-track bytes. */
  compressedTracks: Buffer
  /** Tuanjie's decoder map, empty when the clip carries none. */
  decoderMap: Array<number>
}

/**
 * The header of one ACL compressed-track blob.
 *
 * Enough to decide whether a caller's decoder can handle it, without
 * decompressing anything.
 *
 * The state flags stay separate booleans rather than the packed bits Core
 * keeps them in: this is a JavaScript-facing shape, and a bitfield would only
 * move the unpacking to the other side.
 */
export interface AclTracks {
  declaredSize: number
  storedHash: number
  version: number
  trackType: string
  trackCount: number
  samplesPerTrack: number
  sampleRate: number
  decompressedValueCount: bigint
  hasMetadata: boolean
  isWrapOptimized: boolean
  hasDatabase: boolean
  hasStrippedKeyframes: boolean
}

/**
 * Complete bounded `AnimationClip` shape, muscle, ACL, and streaming metadata.
 *
 * Core still parses the complete object and validates ordinary keyframes;
 * their arrays stay in Rust and are summarized by counts rather than copied
 * into JavaScript. Separate booleans rather than a bitfield keep callers from
 * having to reproduce Core's decoding.
 */
export interface AnimationClipInfo {
  pathId: bigint
  name: string
  sampleRate: number
  wrapMode: number
  legacy: boolean
  compressed: boolean
  useHighQualityCurve: boolean
  rotationCurveCount: number
  positionCurveCount: number
  scaleCurveCount: number
  eulerCurveCount: number
  floatCurveCount: number
  pptrCurveCount: number
  muscleClipSize: number
  /** Present when the clip carries muscle (humanoid) data. */
  hasMuscleClip: boolean
  streamedCurveCount?: number
  denseCurveCount?: number
  constantValueCount?: number
  hasAcl: boolean
  aclFrameCount?: number
  aclBoneCount?: number
  aclSampleRate?: number
  aclCurveCount?: number
  aclTrackByteCount?: bigint
  aclDecoderCount?: number
  aclUseFastSampleMode?: boolean
  /** Present when the clip's samples live in a sibling resource file. */
  hasStreamingInfo: boolean
  streamingOffset?: bigint
  streamingSize?: number
  streamingPath?: string
}

/** One original-to-replacement clip entry in an override controller. */
export interface AnimationClipOverrideInfo {
  originalClip: ObjectReference
  overrideClip: ObjectReference
}

/** An `AnimatorController`'s identity and the clips it references. */
export interface AnimatorControllerInfo {
  name: string
  /** Transform-path strings the controller's bindings resolve through. */
  tosEntryCount: number
  animationClipPathIds: Array<bigint>
}

/** Stable references from one Unity `AnimatorOverrideController`. */
export interface AnimatorOverrideControllerInfo {
  pathId: bigint
  name: string
  controller: ObjectReference
  clipOverrides: Array<AnimationClipOverrideInfo>
  trailingBytes: bigint
}

/** One named entry in an `AssetBundle` container table. */
export interface AssetBundleContainerEntry {
  key: string
  preloadIndex: number
  preloadSize: number
  asset: ObjectReference
}

/** Bounded, ordered metadata from one Unity `AssetBundle`. */
export interface AssetBundleInfo {
  pathId: bigint
  name: string
  objectName: string
  assetBundleName?: string
  preloadTable: Array<ObjectReference>
  container: Array<AssetBundleContainerEntry>
  dependencies: Array<string>
  isStreamedSceneAssetBundle: boolean
}

/** One `AudioClip`'s stored payload and the extension its container implies. */
export interface AudioClip {
  name: string
  /** The extension the stored bytes carry, `.fsb` or `.wav` for example. */
  extension: string
  /**
   * `audio_raw` for the serialized payload or `audio_wav` for a verified
   * decoder-free WAV materialization.
   */
  payloadKind: string
  /** True when Core can produce WAV bytes without an external decoder. */
  isDirectWav: boolean
  data: Buffer
}

/**
 * Complete stable skeleton, TOS, and human-description metadata from an
 * `Avatar`.
 */
export interface Avatar {
  pathId: bigint
  name: string
  /** Compatibility alias retained for callers of the original Node slice. */
  declaredSize: number
  /** The size the object declares for its constant block. */
  declaredAvatarSize: number
  skeletonNodeCount: number
  humanSkeletonNodeCount: number
  /**
   * Bone path entries, retained in order so duplicate hashes keep Unity's
   * first-hit behaviour.
   */
  pathCount: number
  paths: Array<AvatarPathEntry>
  hasHumanDescription: boolean
  humanBoneCount: number
  skeletonBoneCount: number
  rootMotionBoneName?: string
}

/** One ordered Avatar TOS path entry. */
export interface AvatarPathEntry {
  hash: number
  path: string
}

/**
 * A resident binary asset: a `Font`, a legacy `MovieTexture`, or a `VideoClip`.
 *
 * All three are a name and a blob whose format the file declares, so one shape
 * covers them rather than three that differ only in what they are called.
 */
export interface BinaryAsset {
  name: string
  /** What the payload is, as the reader classified it. */
  kind: string
  /** The extension the stored bytes carry, `.ttf` or `.ogg` for example. */
  extension: string
  data: Buffer
}

/** The scene lists a `BuildSettings` object records. */
export interface BuildSettings {
  /** Pre-5.x level paths, absent on newer layouts. */
  levels?: Array<string>
  /** 5.x and newer scene paths, absent on older layouts. */
  scenes?: Array<string>
}

/** One real Unity `AnimationClip` projected to Cubism motion3 JSON. */
export interface CubismClipMotion {
  fileIndex: number
  pathId: bigint
  name: string
  duration: number
  fps: number
  curveCount: number
  keyframeCount: number
  eventCount: number
  json: Buffer
}

/** One embedded-schema Cubism display-info component. */
export interface CubismDisplayInfo {
  pathId: bigint
  name: string
  displayName?: string
  /** `displayName` when it is non-empty, otherwise `name`. */
  effectiveName: string
}

/**
 * One Cubism document produced from a single behaviour.
 *
 * The bytes are the document itself; the counts alongside are what a caller
 * would otherwise have to parse the JSON to learn.
 */
export interface CubismDocument {
  name: string
  /** The document's own JSON text. */
  json: Buffer
  /**
   * Sub-rigs for physics, parameters for an expression, curves for a
   * motion. Zero for a document that has no such notion.
   */
  entryCount: number
}

/** Parameter and part identifiers used to resolve `AnimationClip` bindings. */
export interface CubismMotionTargets {
  parameters?: Array<string>
  parts?: Array<string>
}

/** One embedded-schema `CubismPosePart` component. */
export interface CubismPosePart {
  pathId: bigint
  groupIndex: number
  links: Array<string>
}

/** Options for encoding one decoded RGBA image into a file payload. */
export interface EncodeImageOptions {
  /** `jpeg`, `png`, `bmp`, `tga`, `webp`, or `raw-rgba`. Defaults to `png`. */
  imageFormat?: string
  /** JPEG-only quality from 1 through 100. Defaults to 75. */
  jpegQuality?: number
  /**
   * JPEG-only chroma subsampling: `auto`, `4:4:4`, `4:2:2`, or `4:2:0`.
   * Defaults to `auto`, the encoder's quality-driven choice.
   */
  jpegSampling?: string
  /** JPEG-only: write a progressive stream instead of a baseline one. */
  jpegProgressive?: boolean
  /** JPEG-only: spend extra encode CPU on optimized Huffman tables. */
  jpegOptimizedHuffman?: boolean
  /**
   * JPEG-only `[r, g, b]` background compositing translucent pixels
   * before encoding. Omitted, alpha is discarded outright, matching the
   * managed exporter.
   */
  jpegBackground?: Array<number>
  /**
   * PNG-only zlib effort: `fast`, `default`, `best`, or an explicit
   * numeric level 0 through 9. Defaults to `default`. Every level is
   * lossless; the effort trades encode CPU for file size.
   */
  compression?: string | number
  /**
   * PNG-only scanline filter strategy: `auto`, `none`, or `adaptive`.
   * Every choice is lossless. The default `auto` follows the compression
   * choice — adaptive filtering under the fdeflate `fast` effort, whose
   * output barely compresses unfiltered, and the historical unfiltered
   * scanlines under the flate2 levels, where filtering costs CPU without
   * buying size on decoded-texture content.
   */
  pngFilter?: string
  /** Cap on the encoded output length in bytes. Defaults to 512 MiB. */
  maximumBytes?: number
}

/**
 * Complete caller-configurable Core export policy.
 *
 * Every field is optional and preserves Core's default when omitted. The
 * older `export(outputRoot, overwrite?)` method remains available as the
 * compact compatibility call.
 */
export interface ExportConfiguration {
  /** `auto`, `raw`, `typetree-json`, or `dump-text`. */
  mode?: string
  /** `asset-name`, `asset-name-path-id`, or `path-id`. */
  filenameFormat?: string
  /** `jpeg`, `png`, `bmp`, `tga`, `webp`, or `raw-rgba`. */
  imageFormat?: string
  jpegQuality?: number
  /** `auto`, `raw`, or `wav`. */
  audioFormat?: string
  overwriteExisting?: boolean
  restoreTextAssetExtension?: boolean
  prettyJson?: boolean
  maximumObjects?: number
  maximumTotalOutputBytes?: number
  maximumMetadataBytes?: number
  maximumRawObjectBytes?: number
  maximumTypeTreeJsonBytes?: number
  maximumTypeTreeDumpBytes?: number
  maximumTextAssetBytes?: number
  maximumSimpleAssetBytes?: number
  maximumAudioOutputBytes?: number
  maximumTextureOutputBytes?: number
  maximumTextureArrayOutputBytes?: number
  maximumTextureArrayBundleBytes?: number
  maximumSpriteOutputBytes?: number
  maximumShaderOutputBytes?: number
  maximumMonobehaviourJsonBytes?: number
  maximumMeshObjectBytes?: number
  maximumMeshOutputBytes?: number
}

/** One object the exporter could not write, and why. */
export interface ExportFailure {
  source: string
  pathId: bigint
  classId: number
  error: string
}

/** One object the exporter wrote. */
export interface ExportRecord {
  source: string
  pathId: bigint
  classId: number
  outputPath: string
  /** What the bytes are, `image_png` or `mesh_obj` for example. */
  payloadKind: string
}

/**
 * What an export run produced. Failures are reported rather than thrown so
 * one unreadable object does not cost the whole run.
 */
export interface ExportReport {
  exported: Array<ExportRecord>
  failures: Array<ExportFailure>
  /**
   * Objects declined by design rather than broken, kept separate so a
   * caller can tell "this build carries shaders we do not read" from "the
   * export went wrong".
   */
  unsupported: Array<ExportFailure>
}

/** What an extraction run produced. */
export interface ExtractionReport {
  extractedCount: number
  skippedExistingCount: number
  failureCount: number
  outputBytes: bigint
}

/** One `GameObject` branch that can be exported as its own FBX. */
export interface FbxCandidate {
  fileIndex: number
  pathId: bigint
  /** The Animator that owns this branch, when one does. */
  animatorFileIndex?: number
  animatorPathId?: bigint
  name: string
}

export interface FileInfo {
  index: number
  path: string
  unityVersion: string
  objectCount: number
}

/** Stable references from one legacy Unity `Animation` component. */
export interface LegacyAnimationInfo {
  pathId: bigint
  gameObject: ObjectReference
  enabled: number
  defaultClip: ObjectReference
  clips: Array<ObjectReference>
  trailingBytes: bigint
}

/**
 * Something a package could not carry, and why.
 *
 * A Live2D model routinely resolves partly: a fade-motion list points at a
 * clip in a bundle that was not loaded, or a component's schema is not
 * available. Discovery keeps going, and these say what was left out. Without
 * them a short package looks like a complete one.
 */
export interface Live2DDiagnostic {
  fileIndex: number
  pathId: bigint
  kind: string
  detail: string
}

/** One file belonging to a materialized Live2D package. */
export interface Live2DFile {
  /** Path relative to the package directory. */
  fileName: string
  data: Buffer
}

/** One materialized Live2D model: every file it needs, in memory. */
export interface Live2DPackageFiles {
  name: string
  directoryName: string
  files: Array<Live2DFile>
}

/** One Live2D model discovered in the collection. */
export interface Live2DPackageInfo {
  name: string
  directoryName: string
  mocFileName: string
  textureCount: number
  expressionCount: number
  motionCount: number
  hasPhysics: boolean
  hasPose: boolean
  hasDisplayInfo: boolean
}

/** Materialized packages and what discovery could not include. */
export interface Live2DPackageSet {
  packages: Array<Live2DPackageFiles>
  diagnostics: Array<Live2DDiagnostic>
}

export interface LoadDiagnosticInfo {
  path: string
  message: string
}

/** A `Material`'s shader reference and its named property sheets. */
export interface Material {
  name: string
  shaderFileId: number
  shaderPathId: bigint
  textureProperties: Array<string>
  floatProperties: Array<string>
  colorProperties: Array<string>
}

/** One in-memory input for a multi-file open. */
export interface MemoryInput {
  name: string
  data: Buffer
}

/**
 * A scene written as Wavefront OBJ, with the files it names.
 *
 * The OBJ's `mtllib` line names the material library and the library's
 * `map_*` lines name the textures, all resolved by file name against the
 * OBJ's own directory. They come back rather than being written because this
 * call has no directory of its own, and splitting them across directories
 * breaks the references.
 */
export interface ModelObj {
  obj: Buffer
  materialLibraryName: string
  materialLibrary: Buffer
  textures: Array<Live2DFile>
  /**
   * Texture references this reader could not resolve or decode, with the
   * reason.
   */
  skipped: Array<string>
}

/** Caller-configurable budgets for textures returned beside a model. */
export interface ModelTextureLimits {
  maximumTextureReferences?: number
  maximumTextures?: number
  maximumNameIndexBytes?: number
  maximumMetadataBytes?: number
  maximumTotalEncodedBytes?: number
  maximumSingleTextureBytes?: number
}

/** A `MonoBehaviour` read as JSON, and which tree it was read through. */
export interface MonoBehaviourJson {
  json: Buffer
  /**
   * `"embedded"` when the file carried its own type tree, `"schema"` when
   * the layout came from a supplied schema. Worth distinguishing: a value
   * read through a schema is only as good as that schema.
   */
  source: string
}

/** A complete object schema for one managed script type. */
export interface MonoBehaviourSchema {
  assemblyName: string
  className: string
  namespace?: string
  /**
   * Exact Unity version this schema was generated for. Omit for a schema
   * that applies to every version.
   */
  unityVersion?: string
  nodes: Array<SchemaNode>
}

/**
 * The identity fields of a `MonoScript`, which name the type a
 * `MonoBehaviour` deserializes as.
 */
export interface MonoScript {
  name: string
  className: string
  namespace: string
  assemblyName: string
  executionOrder?: number
}

export interface ObjectInfo {
  fileIndex: number
  objectIndex: number
  sourcePath: string
  pathId: bigint
  classId: number
  byteSize: bigint
  name?: string
  container?: string
}

/** One Unity serialized-object pointer. */
export interface ObjectReference {
  fileId: number
  pathId: bigint
}

/**
 * How an input is opened.
 *
 * Every field is optional and omitting one keeps Core's default. This exists
 * because the alternatives do not combine: a separate factory per option
 * cannot open a UnityCN-encrypted bundle whose header version was also
 * stripped, which is an ordinary pair of facts about one file.
 */
export interface OpenOptions {
  /**
   * Parse against this version instead of the one the files declare, for
   * files whose own version was stripped at build time.
   */
  unityVersion?: string
  /**
   * The 16-byte UnityCN key for an encrypted archive.
   *
   * Caller-supplied only: this project ships no key material, and none is
   * recovered from anything. The key is never printed, including in error
   * text.
   */
  unityCnKey?: Buffer
  /**
   * Keep the inputs that parsed instead of refusing the whole load over one
   * that did not. A game directory routinely mixes readable assets with
   * encrypted or not-yet-supported containers.
   */
  skipUnreadableInputs?: boolean
  /**
   * Reject classes whose standard-Unity version is above the verified
   * ceiling instead of attempting the newest known layout (the default).
   */
  strictUnityVersions?: boolean
  maximumInputFiles?: number
  maximumInputDirectories?: number
  maximumDirectoryEntries?: number
  /** Maximum UTF-8 bytes in one root label or fully qualified nested path. */
  maximumPathBytes?: number
  /** Maximum cumulative UTF-8 bytes of paths discovered during one load. */
  maximumTotalPathBytes?: number
  /** Maximum cumulative UTF-8 bytes retained by skipped-input diagnostics. */
  maximumDiagnosticBytes?: number
}

/** The identity fields of a `PlayerSettings` object. */
export interface PlayerSettings {
  companyName: string
  productName: string
}

/** Bounded, ordered metadata from one Unity `PreloadData`. */
export interface PreloadDataInfo {
  pathId: bigint
  name: string
  assets: Array<ObjectReference>
}

export interface ResourceInfo {
  index: number
  path: string
  byteSize: bigint
}

/** One named entry in a `ResourceManager` container table. */
export interface ResourceManagerContainerEntry {
  key: string
  asset: ObjectReference
}

/** Bounded, ordered metadata from one Unity `ResourceManager`. */
export interface ResourceManagerInfo {
  pathId: bigint
  container: Array<ResourceManagerContainerEntry>
}

/** A decoded RGBA8 image. */
export interface RgbaImage {
  width: number
  height: number
  /**
   * Tightly packed RGBA8 rows in display order: the first row is the top
   * edge of the image, matching the Python binding and the CLI's encoded
   * output. `Texture2D` decoders work bottom-up, so these rows have already
   * been flipped.
   */
  pixels: Buffer
}

/** Caller-configurable collection-wide scene assembly budgets. */
export interface SceneLimits {
  maximumGameObjects?: number
  maximumTotalComponents?: number
  maximumTotalTransformChildReferences?: number
  maximumTotalMaterialReferences?: number
  maximumTotalBoneReferences?: number
  maximumHierarchyEdges?: number
  maximumIndexBytes?: number
}

/**
 * One `GameObject` in the assembled hierarchy.
 *
 * The component flags are separate booleans rather than a bitfield because
 * this is a JavaScript-facing shape and a bitfield would need decoding on the
 * other side.
 */
export interface SceneNode {
  fileIndex: number
  pathId: bigint
  name: string
  /** Absent for a `GameObject` with no `Transform`, which cannot be placed. */
  parentPathId?: bigint
  childCount: number
  hasTransform: boolean
  hasMeshRenderer: boolean
  hasSkinnedMeshRenderer: boolean
  hasAnimator: boolean
}

/**
 * One node of a trusted managed object schema.
 *
 * Reconstructed by an offline tool; nothing here executes asset-controlled
 * code. `align` sets the four-byte alignment flag Unity's own trees carry.
 */
export interface SchemaNode {
  typeName: string
  fieldName: string
  /** Nesting depth, zero for the root. */
  level: number
  align: boolean
}

/** Complete, bounded metadata from one Unity `SpriteAtlas` object. */
export interface SpriteAtlasInfo {
  pathId: bigint
  name: string
  packedSprites: Array<ObjectReference>
  packedSpriteNames: Array<string>
  renderDataEntries: Array<SpriteAtlasRenderData>
  tag: string
  isVariant: boolean
}

export interface SpriteAtlasRect {
  x: number
  y: number
  width: number
  height: number
}

/** Complete crop, texture and packing metadata for one atlas key. */
export interface SpriteAtlasRenderData {
  key: SpriteAtlasRenderDataKey
  texture: ObjectReference
  alphaTexture: ObjectReference
  textureRect: SpriteAtlasRect
  textureRectOffset: SpriteAtlasVector2
  atlasRectOffset: SpriteAtlasVector2
  uvTransform: SpriteAtlasVector4
  downscaleMultiplier: number
  settings: SpriteAtlasSettings
  /** Absent before Unity 2020.2; present and possibly empty afterwards. */
  secondaryTextures?: Array<SpriteAtlasSecondaryTexture>
}

/** Serialized composite key used by one `SpriteAtlas` render-data entry. */
export interface SpriteAtlasRenderDataKey {
  /** GUID bytes in Unity's original serialized order. */
  guidBytes: Buffer
  value: bigint
}

export interface SpriteAtlasSecondaryTexture {
  texture: ObjectReference
  name: string
}

/** Raw and decoded `SpriteSettings` bits. */
export interface SpriteAtlasSettings {
  raw: number
  packed: boolean
  packingMode: number
  packingRotation: number
  meshType: number
}

export interface SpriteAtlasVector2 {
  x: number
  y: number
}

export interface SpriteAtlasVector4 {
  x: number
  y: number
  z: number
  w: number
}

/** Complete, bounded metadata from one Unity `Sprite` object. */
export interface SpriteMetadata {
  objectIndex: number
  pathId: bigint
  name: string
  rect: SpriteRect
  offset: SpriteVector2
  border: SpriteVector4
  pixelsToUnits: number
  pivot: SpriteVector2
  extrude: number
  isPolygon: boolean
  renderDataKey?: SpriteAtlasRenderDataKey
  atlasTags: Array<string>
  spriteAtlas: ObjectReference
  renderData: SpriteRenderData
}

/** Caller-configurable budgets for metadata-only `Sprite` parsing. */
export interface SpriteMetadataLimits {
  maximumEntries?: number
  maximumStringBytes?: number
  maximumTotalStringBytes?: number
  maximumMeshBytes?: number
}

export interface SpriteRect {
  x: number
  y: number
  width: number
  height: number
}

/** Complete resident render metadata stored directly on one `Sprite`. */
export interface SpriteRenderData {
  texture: ObjectReference
  alphaTexture: ObjectReference
  secondaryTextures: Array<SpriteSecondaryTexture>
  textureRect: SpriteRect
  textureRectOffset: SpriteVector2
  atlasRectOffset: SpriteVector2
  settings: SpriteSettings
  uvTransform: SpriteVector4
  downscaleMultiplier: number
  meshTriangles: Array<SpriteTriangle>
}

export interface SpriteSecondaryTexture {
  texture: ObjectReference
  name: string
}

/** Raw and decoded `SpriteSettings` bits from resident render data. */
export interface SpriteSettings {
  raw: number
  packed: boolean
  packingMode: string
  packingRotation: number
  meshType: string
}

/** One validated local-space triangle used for tight-mesh masking. */
export interface SpriteTriangle {
  first: SpriteVector2
  second: SpriteVector2
  third: SpriteVector2
}

export interface SpriteVector2 {
  x: number
  y: number
}

export interface SpriteVector4 {
  x: number
  y: number
  z: number
  w: number
}

/** An FBX plus the texture files it references by name. */
export interface TexturedFbx {
  fbx: Buffer
  /** Each must be written beside the FBX for its reference to resolve. */
  textures: Array<Live2DFile>
  /**
   * Texture references this reader could not resolve or decode, with the
   * reason. Reported rather than raised so one bad texture does not cost the
   * model.
   */
  skipped: Array<string>
}
